### ISSUE TITLE
Deprecate Cloud Template Versioning

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#104]
### Description

Deprecate support for versioning in Cloud Templates.

Currently Cloud Template versioning serves little to no purpose. 

When pushing versions to a greenfield environment, fake versions are created (just the metadata) with no change in the actual behavior. 

The only time it makes sense is to unrelease and release versions on an existing deployment.

Is this needed?

## Proposal:

1. Release a new version:
 - If there already is a cloud template existing and the contents are not the same
2. Create a cloud template and release one version 
- If there is NO cloud template
3. New Flag that will "unrelease" older versions of the cloud template and keep only the latest
 - Defaults to true
 - If set as false, no changes will be done. Releasing/Unreleasing must be handled manually
 - If set to true, unrelease all previous versions.
4. Remove old bp flags
5. Modify the installer as well
 - Introduce the new variable

Internal link to ticket that implemented this change: https://jira.pscoe.vmware.com/browse/IAC-459

**Comment by carlosaya** [comment]
I'd be ok with this.  As you stated, they aren't real versions anyway. And given we are using build tools, everything is in source control of we need to roll back.

**Comment by Michaelpalacce** [comment]
Originally we wanted to keep the versions in sync between different environments (at least their count)

Another thing to note:

- When releasing a new version, the idea was to not release it if the contents are identical

**Comment by ynedelchev** [comment]
I think it makes sense to keep historical versions to be able to revert back to them.
 
Imagine, you create a new build, which is deployed on customer env, but it breaks the process flow because of an issue in Cloud Template. Then you would like to a previous version from previous deploy. 

However, in the past we have seen customer complains that we version a Cloud Template even if there is not change in it. 
If we can skip that for unchanged Cloud Templates, that would be great.

**Comment by Michaelpalacce** [comment]
> I think it makes sense to keep historical versions to be able to revert back to them.
> 
> Imagine, you create a new build, which is deployed on customer env, but it breaks the process flow because of an issue in Cloud Template. Then you would like to a previous version from previous deploy.
> 
> However, in the past we have seen customer complains that we version a Cloud Template even if there is not change in it. If we can skip that for unchanged Cloud Templates, that would be great.

@ynedelchev Good points. Will take these into consideration. 

I updated the ticket with a proposal, will update it as needed

**Comment by Michaelpalacce** [comment]
Triaged internally. We will move forward with the removal of cloud template versions
