### ISSUE TITLE
Pushing and pulling from/to vRA 8.12 fails with buildtools 2.32.0

### ISSUE THREAD

**Issue by hstraten** [vmware/build-tools-for-vmware-aria#108]
### Description

Pushing and pulling packages to vRA tenants

### Steps to Reproduce

1. create XaaS with custom form
2. create content.yaml
3. try a mvn vra-ng:pull

**Preconditions:** 
Set buildtools version 2.32.0

**Expected behavior:** 
package created with form json file

**Actual behavior:**
error 404

**Reproduces how often:**
100%

**Component/s:**
"maven/plugins/vra-ng"

**Affects Build/s:**
at least 2.32.0

#### Client

-   Build Tools for VMware Aria Version: 2.32.0
-   Visual Studio Code Version: 1.78
-   OS Version: macOS Ventura 13.4

#### Server

-   vRealize Automation Version: 8.12.0.30728 (21622235)
-   vRealize Orchestrator Version: 8.12.0.21583018
-   vRealize Operations Version: 8.12.0 (21594884)
-   vRealize Log Insight Version: 8.12.0-21618456

### Failure Logs
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for nl.----.---:catalogItemName:vra-ng:1.0.2
[WARNING] 'parent.relativePath' of POM nl.---.--:catalogItemName:1.0.2 (//src/vRealize code/catalogItems/catalogItemName/vra/pom.xml) points at nl.---.--:catalogItemName-all instead of com.vmware.pscoe.vra-ng:vra-ng-package, please verify your project structure @ line 5, column 11
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -------------------< nl.---.--:catalogItemName >--------------------
[INFO] Building catalogItemName 1.0.2
[INFO] -------------------------------[ vra-ng ]-------------------------------
[INFO] 
[INFO] --- vra-ng-package-maven-plugin:2.32.0:pull (default-cli) @ catalogItemName ---
[INFO] Reading config for type : VRANG
[INFO] Searching for Package Store for type VRANG
[INFO] Detected ConfigurationVraNg
[INFO] Acquiring with refresh token
[INFO] Creating configuration for VRA NG
com.vmware.pscoe.iac.artifact.model.vrang.VraNgPackageDescriptor@634e1b39[
  catalogItem=[Application Segmentation Tags__Application Segmentation Tags]
  blueprint=[]
  subscription=[]
  flavorMapping=[]
  imageMapping=[]
  storageProfile=[]
  catalogEntitlement=[]
  propertyGroup=<null>
  regionMapping=com.vmware.pscoe.iac.artifact.model.vrang.VraNgRegionMapping@4d81e83a
  customResource=[]
  resourceAction=[]
  contentSource=[Application Segmentation Tags]
  policy=<null>
]
[INFO] Nothing/null passed exporting everything
[ERROR] Error fetching content sharing policy
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.433 s
[INFO] Finished at: 2023-05-23T09:49:01+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.32.0:pull (default-cli) on project catalogItemName: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.32.0:pull failed: org.springframework.web.client.HttpClientErrorException: 404 Not Found {"message":"No value present","statusCode":404,"errorCode":0} -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Push log is similar but a more extensive error message:
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.32.0:push (default-cli) on project catalogItemName: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.32.0:push failed: Cannot invoke "com.vmware.pscoe.iac.artifact.model.vrang.VraNgCatalogItemType.getId()" because "this.type" is null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.32.0:push (default-cli) on project catalogItemName: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.32.0:push failed: Cannot invoke "com.vmware.pscoe.iac.artifact.model.vrang.VraNgCatalogItemType.getId()" because "this.type" is null

### Additional Context
content.yaml:

blueprint: []
subscription: []
flavor-mapping: []
image-mapping: []
storage-profile: []
region-mapping:
  cloud-account-tags:
    export-tag:
    import-tags: []
catalog-item:
  - Catalog Item Name__Catalog Item Name
custom-resource: []
resource-action: []
catalog-entitlement: []
content-source:
  - Catalog Item Name

**Comment by Michaelpalacce** [comment]
Hey @hstraten, thank you for the issue! 

Can you add:

```yaml
policy:
  content-sharing:
```

to your content.yaml?

**Comment by Rehiq** [comment]
Hey @mdittbrenner215,

Thanks for sharing the case. I am looking into it.

**Comment by Rehiq** [comment]
The issue occurred because the build tools didn't take into account the association for Catalog Items, it did only for Content Sources.

**Comment by hstraten** [comment]
> ```yaml
> policy:
>   content-sharing:
> ```

Adding just `policy:
  content-sharing:`

still results in a 404, however by adding `policy:
  content-sharing: []` it works

**Comment by mdittbrenner215** [comment]
Is there a document on how to build the iac file for a release?  I need to upload our files to a share to pull down but the only instructions to set up I see are around using a release, but not how to configure from source to release.

**Comment by Michaelpalacce** [comment]
@mdittbrenner215 

1. Download the toolchain
2. Checkout PR branch
3. mvn clean install -DskipTests -> in the root
4. Go to the failing project and set the version to 2.32.1-SNAPSHOT and try again

This is how you can test the toolchain

**Comment by mdittbrenner215** [comment]
I cant get that branch to build properly 

```
> @vmware-pscoe/vrotest@2.32.1-SNAPSHOT build /Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest
> gulp build

[11:12:11] Requiring external module ts-node/register
[11:12:13] Using gulpfile ~/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/gulpfile.ts
[11:12:13] Starting 'build'...
[11:12:13] Starting 'clean'...
[11:12:13] Finished 'clean' after 41 ms
[11:12:13] Starting 'compile'...
[11:12:13] Executing 'node_modules/.bin/tsc --project tsconfig.json'...
[11:12:19] Finished 'compile' after 5.88 s
[11:12:19] Starting 'bundle'...
[11:12:25] Finished 'bundle' after 6.19 s
[11:12:25] Starting 'test'...
[11:12:25] Executing 'node_modules/.bin/tsc --project e2e/tsconfig.json'...
[11:12:31] Executing '/usr/local/bin/node e2e/build/runner.js'...
/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/minimatch/dist/cjs/ast.js:86
    #fillNegs() {
             ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/minimatch/dist/cjs/index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[11:12:31] 'test' errored after 5.99 s
[11:12:31] Error: One or more test cases failed.
    at formatError (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (events.js:326:22)
    at Gulp.EventEmitter.emit (domain.js:483:12)
    at Object.error (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/now-and-later/lib/mapSeries.js:47:14)
    at f (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/once/once.js:25:25)
    at f (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/once/once.js:25:25)
    at tryCatch (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/async-done/index.js:24:15)
    at done (/Users/mdittb638/Documents/code/build-tools-for-vmware-aria/typescript/vrotest/node_modules/async-done/index.js:40:12)
[11:12:31] 'build' errored after 18 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vmware-pscoe/vrotest@2.32.1-SNAPSHOT build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vmware-pscoe/vrotest@2.32.1-SNAPSHOT build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mdittb638/.npm/_logs/2023-06-01T15_12_31_941Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Build Tools for VMware Aria 2.32.1-SNAPSHOT:
[INFO] 
[INFO] Build Tools for VMware Aria ........................ SUCCESS [ 52.258 s]
[INFO] o11n-project ....................................... SUCCESS [ 21.780 s]
[INFO] artifact-manager ................................... SUCCESS [ 10.917 s]
[INFO] base-archetype ..................................... SUCCESS [  0.282 s]
[INFO] package-actions-archetype .......................... SUCCESS [  2.403 s]
[INFO] package-xml-archetype .............................. SUCCESS [  0.101 s]
[INFO] package-mixed-archetype ............................ SUCCESS [  0.151 s]
[INFO] package-vrealize-archetype ......................... SUCCESS [  0.126 s]
[INFO] package-vra-archetype .............................. SUCCESS [  0.126 s]
[INFO] package-vra-ng-archetype ........................... SUCCESS [  0.160 s]
[INFO] package-typescript-archetype ....................... SUCCESS [  0.141 s]
[INFO] package-ts-vra-ng-archetype ........................ SUCCESS [  0.268 s]
[INFO] package-vcd-ng-archetype ........................... SUCCESS [  0.129 s]
[INFO] package-vrops-archetype ............................ SUCCESS [  0.073 s]
[INFO] package-vrli-archetype ............................. SUCCESS [  0.101 s]
[INFO] package-bsc-archetype .............................. SUCCESS [  0.059 s]
[INFO] package-npmconv-archetype .......................... SUCCESS [  0.103 s]
[INFO] package-polyglot-archetype ......................... SUCCESS [  0.127 s]
[INFO] package-cs-archetype ............................... SUCCESS [  0.089 s]
[INFO] common ............................................. SUCCESS [  1.506 s]
[INFO] base-maven-plugin .................................. SUCCESS [ 11.950 s]
[INFO] o11n-actions-package-maven-plugin .................. SUCCESS [  2.846 s]
[INFO] vrealize-package-maven-plugin ...................... SUCCESS [  2.382 s]
[INFO] o11n-typescript-package-maven-plugin ............... SUCCESS [  2.490 s]
[INFO] o11n-polyglot-package-maven-plugin ................. SUCCESS [  2.291 s]
[INFO] abx-package-maven-plugin ........................... SUCCESS [  2.221 s]
[INFO] vra-package-maven-plugin ........................... SUCCESS [  2.201 s]
[INFO] vra-ng-package-maven-plugin ........................ SUCCESS [  2.192 s]
[INFO] o11n-xml-package-maven-plugin ...................... SUCCESS [  2.493 s]
[INFO] vcd-ng-package-maven-plugin ........................ SUCCESS [  2.152 s]
[INFO] vrops-package-maven-plugin ......................... SUCCESS [  2.330 s]
[INFO] vrli-package-maven-plugin .......................... SUCCESS [  2.234 s]
[INFO] bsc-package-maven-plugin ........................... SUCCESS [  2.206 s]
[INFO] ssh-maven-plugin ................................... SUCCESS [  2.268 s]
[INFO] cs-package-maven-plugin ............................ SUCCESS [  2.172 s]
[INFO] base-package ....................................... SUCCESS [  0.015 s]
[INFO] lib ................................................ SUCCESS [  0.014 s]
[INFO] iac-assembly ....................................... SUCCESS [  0.049 s]
[INFO] vropkg ............................................. SUCCESS [01:04 min]
[INFO] polyglotpkg ........................................ SUCCESS [  9.155 s]
[INFO] polyglot-project ................................... SUCCESS [  7.135 s]
[INFO] base-type .......................................... SUCCESS [  0.029 s]
[INFO] node ............................................... SUCCESS [  3.121 s]
[INFO] jasmine ............................................ SUCCESS [  1.216 s]
[INFO] ecmascript ......................................... SUCCESS [  1.320 s]
[INFO] tslib .............................................. SUCCESS [  1.118 s]
[INFO] vrotsc-annotations ................................. SUCCESS [  1.124 s]
[INFO] o11n-core .......................................... SUCCESS [  1.230 s]
[INFO] o11n-plugin-activedirectory ........................ SUCCESS [  1.116 s]
[INFO] o11n-plugin-amqp ................................... SUCCESS [  1.215 s]
[INFO] o11n-plugin-apic ................................... SUCCESS [  1.239 s]
[INFO] o11n-plugin-azure .................................. SUCCESS [  1.221 s]
[INFO] o11n-plugin-dynamictypes ........................... SUCCESS [  1.209 s]
[INFO] o11n-plugin-mail ................................... SUCCESS [  1.212 s]
[INFO] o11n-plugin-mqtt ................................... SUCCESS [  1.273 s]
[INFO] o11n-plugin-net .................................... SUCCESS [  1.226 s]
[INFO] o11n-plugin-nsx .................................... SUCCESS [  1.095 s]
[INFO] o11n-plugin-powershell ............................. SUCCESS [  1.233 s]
[INFO] o11n-plugin-rest ................................... SUCCESS [  1.134 s]
[INFO] o11n-plugin-snmp ................................... SUCCESS [  1.121 s]
[INFO] o11n-plugin-soap ................................... SUCCESS [  1.214 s]
[INFO] o11n-plugin-sql .................................... SUCCESS [  1.109 s]
[INFO] o11n-plugin-ssh .................................... SUCCESS [  1.121 s]
[INFO] o11n-plugin-vapi ................................... SUCCESS [  1.225 s]
[INFO] o11n-plugin-vc ..................................... SUCCESS [  1.223 s]
[INFO] o11n-plugin-vcac ................................... SUCCESS [  1.194 s]
[INFO] o11n-plugin-vcaccafe ............................... SUCCESS [  1.104 s]
[INFO] o11n-plugin-vcloud ................................. SUCCESS [  1.106 s]
[INFO] o11n-plugin-vco .................................... SUCCESS [  1.134 s]
[INFO] o11n-plugin-xml .................................... SUCCESS [  1.312 s]
[INFO] vro ................................................ SUCCESS [  0.017 s]
[INFO] typescript ......................................... SUCCESS [  0.019 s]
[INFO] vrotsc ............................................. SUCCESS [ 59.668 s]
[INFO] npmconv ............................................ SUCCESS [ 10.622 s]
[INFO] vrotest ............................................ FAILURE [ 25.350 s]
[INFO] vro-scripting-api .................................. SKIPPED
[INFO] installer .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:12 min
[INFO] Finished at: 2023-06-01T11:12:32-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (npm compile) on project vrotest: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :vrotest
➜  build-tools-for-vmware-aria git:(108-pushing-and-pulling-fromto-vra-812-fails-with-buildtools-2320) ✗ 

```

**Comment by mdittbrenner215** [comment]
I built locally but it still cant find the files

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Build Tools for VMware Aria 2.32.1-SNAPSHOT:
[INFO] 
[INFO] Build Tools for VMware Aria ........................ SUCCESS [  1.014 s]
[INFO] o11n-project ....................................... SUCCESS [  2.498 s]
[INFO] artifact-manager ................................... SUCCESS [  9.651 s]
[INFO] base-archetype ..................................... SUCCESS [  0.346 s]
[INFO] package-actions-archetype .......................... SUCCESS [  1.931 s]
[INFO] package-xml-archetype .............................. SUCCESS [  0.223 s]
[INFO] package-mixed-archetype ............................ SUCCESS [  0.203 s]
[INFO] package-vrealize-archetype ......................... SUCCESS [  0.164 s]
[INFO] package-vra-archetype .............................. SUCCESS [  0.116 s]
[INFO] package-vra-ng-archetype ........................... SUCCESS [  0.255 s]
[INFO] package-typescript-archetype ....................... SUCCESS [  0.245 s]
[INFO] package-ts-vra-ng-archetype ........................ SUCCESS [  0.302 s]
[INFO] package-vcd-ng-archetype ........................... SUCCESS [  0.154 s]
[INFO] package-vrops-archetype ............................ SUCCESS [  0.097 s]
[INFO] package-vrli-archetype ............................. SUCCESS [  0.118 s]
[INFO] package-bsc-archetype .............................. SUCCESS [  0.074 s]
[INFO] package-npmconv-archetype .......................... SUCCESS [  0.125 s]
[INFO] package-polyglot-archetype ......................... SUCCESS [  0.147 s]
[INFO] package-cs-archetype ............................... SUCCESS [  0.093 s]
[INFO] common ............................................. SUCCESS [  1.488 s]
[INFO] base-maven-plugin .................................. SUCCESS [ 11.869 s]
[INFO] o11n-actions-package-maven-plugin .................. SUCCESS [  2.853 s]
[INFO] vrealize-package-maven-plugin ...................... SUCCESS [  2.362 s]
[INFO] o11n-typescript-package-maven-plugin ............... SUCCESS [  2.545 s]
[INFO] o11n-polyglot-package-maven-plugin ................. SUCCESS [  2.294 s]
[INFO] abx-package-maven-plugin ........................... SUCCESS [  2.250 s]
[INFO] vra-package-maven-plugin ........................... SUCCESS [  2.227 s]
[INFO] vra-ng-package-maven-plugin ........................ SUCCESS [  2.397 s]
[INFO] o11n-xml-package-maven-plugin ...................... SUCCESS [  2.564 s]
[INFO] vcd-ng-package-maven-plugin ........................ SUCCESS [  2.299 s]
[INFO] vrops-package-maven-plugin ......................... SUCCESS [  2.305 s]
[INFO] vrli-package-maven-plugin .......................... SUCCESS [  2.289 s]
[INFO] bsc-package-maven-plugin ........................... SUCCESS [  2.154 s]
[INFO] ssh-maven-plugin ................................... SUCCESS [  2.292 s]
[INFO] cs-package-maven-plugin ............................ SUCCESS [  2.215 s]
[INFO] base-package ....................................... SUCCESS [  0.025 s]
[INFO] lib ................................................ SUCCESS [  0.015 s]
[INFO] iac-assembly ....................................... SUCCESS [  0.034 s]
[INFO] vropkg ............................................. SUCCESS [ 48.369 s]
[INFO] polyglotpkg ........................................ SUCCESS [  9.831 s]
[INFO] polyglot-project ................................... SUCCESS [  5.666 s]
[INFO] base-type .......................................... SUCCESS [  0.028 s]
[INFO] node ............................................... SUCCESS [  3.069 s]
[INFO] jasmine ............................................ SUCCESS [  2.009 s]
[INFO] ecmascript ......................................... SUCCESS [  1.477 s]
[INFO] tslib .............................................. SUCCESS [  1.897 s]
[INFO] vrotsc-annotations ................................. SUCCESS [  1.439 s]
[INFO] o11n-core .......................................... SUCCESS [  1.354 s]
[INFO] o11n-plugin-activedirectory ........................ SUCCESS [  1.335 s]
[INFO] o11n-plugin-amqp ................................... SUCCESS [  2.136 s]
[INFO] o11n-plugin-apic ................................... SUCCESS [  2.125 s]
[INFO] o11n-plugin-azure .................................. SUCCESS [  1.788 s]
[INFO] o11n-plugin-dynamictypes ........................... SUCCESS [  1.870 s]
[INFO] o11n-plugin-mail ................................... SUCCESS [  1.600 s]
[INFO] o11n-plugin-mqtt ................................... SUCCESS [  1.320 s]
[INFO] o11n-plugin-net .................................... SUCCESS [  1.187 s]
[INFO] o11n-plugin-nsx .................................... SUCCESS [  1.505 s]
[INFO] o11n-plugin-powershell ............................. SUCCESS [  1.497 s]
[INFO] o11n-plugin-rest ................................... SUCCESS [  1.658 s]
[INFO] o11n-plugin-snmp ................................... SUCCESS [  1.424 s]
[INFO] o11n-plugin-soap ................................... SUCCESS [  1.555 s]
[INFO] o11n-plugin-sql .................................... SUCCESS [  1.457 s]
[INFO] o11n-plugin-ssh .................................... SUCCESS [  1.344 s]
[INFO] o11n-plugin-vapi ................................... SUCCESS [  1.572 s]
[INFO] o11n-plugin-vc ..................................... SUCCESS [  1.699 s]
[INFO] o11n-plugin-vcac ................................... SUCCESS [  1.507 s]
[INFO] o11n-plugin-vcaccafe ............................... SUCCESS [  1.497 s]
[INFO] o11n-plugin-vcloud ................................. SUCCESS [  1.335 s]
[INFO] o11n-plugin-vco .................................... SUCCESS [  1.264 s]
[INFO] o11n-plugin-xml .................................... SUCCESS [  1.652 s]
[INFO] vro ................................................ SUCCESS [  0.030 s]
[INFO] typescript ......................................... SUCCESS [  0.019 s]
[INFO] vrotsc ............................................. SUCCESS [ 32.323 s]
[INFO] npmconv ............................................ SUCCESS [ 11.634 s]
[INFO] vrotest ............................................ SUCCESS [ 16.077 s]
[INFO] vro-scripting-api .................................. SUCCESS [  9.710 s]
[INFO] installer .......................................... SUCCESS [ 14.690 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:19 min
[INFO] Finished at: 2023-06-01T11:51:30-04:00
[INFO] ------------------------------------------------------------------------


➜  base-all git:(CBISVM-5476) ✗ mvn -U clean install            
[INFO] Scanning for projects...
Downloading from central: https://yumrepo.sys.comcast.net/xcloud/software/vrbt/repo/maven/com/vmware/pscoe/o11n/base-package/2.32.1-SNAPSHOT/maven-metadata.xml
Downloading from maven: https://repo.maven.apache.org/maven2/com/vmware/pscoe/o11n/base-package/2.32.1-SNAPSHOT/maven-metadata.xml
Downloading from central: https://yumrepo.sys.comcast.net/xcloud/software/vrbt/repo/maven/com/vmware/pscoe/o11n/base-package/2.32.1-SNAPSHOT/base-package-2.32.1-SNAPSHOT.pom
Downloading from maven: https://repo.maven.apache.org/maven2/com/vmware/pscoe/o11n/base-package/2.32.1-SNAPSHOT/base-package-2.32.1-SNAPSHOT.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.vmware.xcloud.o11n:base-all:2.7.12-SNAPSHOT: Could not find artifact com.vmware.pscoe.o11n:base-package:pom:2.32.1-SNAPSHOT in central (https://yumrepo.sys.comcast.net/xcloud/software/vrbt/repo/maven) and 'parent.relativePath' points at no local POM @ line 10, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.vmware.xcloud.o11n:base-all:2.7.12-SNAPSHOT (/Users/mdittb638/sddc_automation/lib/maven/base-all/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.vmware.xcloud.o11n:base-all:2.7.12-SNAPSHOT: Could not find artifact com.vmware.pscoe.o11n:base-package:pom:2.32.1-SNAPSHOT in central (https://yumrepo.sys.comcast.net/xcloud/software/vrbt/repo/maven) and 'parent.relativePath' points at no local POM @ line 10, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
➜  base-all git:(CBISVM-5476) ✗

**Comment by mdittbrenner215** [comment]
@Michaelpalacce @Rehiq 
I was successfully able to pull content now and no 404 with 2.32.1-SNAPSHOT with vRA 8.12.1.

I have not looked yet to see if it fixes the issue with the catalog items issue with 8.11+ with the change in catalog items and versions.  Also havent checked to see if this is backwards compatible with our staging/production env yet either. 

Content-Blueprints__Linux Custom.json
[INFO] Created custom form data file /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/catalog-items/forms/Master-Content-Blueprints__Linux Custom__FormData.json
[WARNING] Icon is SVG, skipping...
[INFO] Storing catalogItem Linux Custom
[INFO] Creating folder: /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/catalog-items
[INFO] Created file /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/catalog-items/Master-Content-Blueprints__Linux Custom.json
[INFO] class com.vmware.pscoe.iac.artifact.store.vrang.VraNgCatalogItemStore812
[INFO] Created custom form metadata file /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/catalog-items/forms/Master-Content-Blueprints__Linux Custom with Extra Disk.json
[INFO] Created custom form data file /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/catalog-items/forms/Master-Content-Blueprints__Linux Custom with Extra Disk__FormData.json
[WARNING] Icon is SVG, skipping...
[INFO] Storing catalogItem Linux Custom with Extra Disk
[INFO] Creating folder: /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/catalog-items
[INFO] Created file /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/catalog-items/Master-Content-Blueprints__Linux Custom with Extra Disk.json
[INFO] Currently exporting: VraNgContentSharingPolicyStore
[INFO] Nothing/null passed exporting everything
[INFO] Created content sharing file /var/folders/by/v62wx8154x33z5bk6bvdw_lm0000gp/T/1685666207072-0/com.comcast.xcloud.vra-2.3.5-SNAPSHOT.vra-ng/policies/content-sharing/xCloudAdmin-1234567890-abcdef_ContentSharingPolicy.json
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.424 s
[INFO] Finished at: 2023-06-01T20:37:06-04:00
[INFO] ------------------------------------------------------------------------

**Comment by carlosaya** [comment]
I am getting the same error on 2.33.0.

```
    <parent>
        <groupId>com.vmware.pscoe.vra-ng</groupId>
        <artifactId>vra-ng-package</artifactId>
        <version>2.33.0</version>
    </parent>
```

```
policy:
  content-sharing:
    - IACToolbox
```

```
[INFO] Currently exporting: VraNgContentSharingPolicyStore
[INFO] Exporting filtered items: [IACToolbox]
[ERROR] Error fetching content sharing policy
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.673 s
[INFO] Finished at: 2023-06-27T07:41:29Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.33.0:pull (default-cli) on project launch-vra: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.33.0:pull failed: org.springframework.web.client.HttpClientErrorException: 404 Not Found {"message":"No value present","statusCode":404,"errorCode":0} -> [Help 1]
```

We only have 8 policies defined in this environment, and 7 of them are content sharing policies, so I would be surprised if this was a paging issue.
