### ISSUE TITLE
Mocking for configuration elements is incorrect

### ISSUE THREAD

**Issue by pe1pip** [vmware/build-tools-for-vmware-aria#110]
### Description

The mocking for configuration elements is incorrect. When there are no attributes in a config element vRO returns null when the attributes of a config element is accessed, in vRBT the mocking returns an empty array. Similarly, the Server.getConfigurationElementCategoryWithPath() should return null for a non-existent category and category.configurationElements should return null for an empty category.

Note that behaviour of category.allConfigurationElements is different, this returns an empty array if there are zero elements in a category.

### Steps to Reproduce

1. inspect this code in 'typescript/vro-scripting-api/src/configurations.ts':
```js
  function getElementAttributes(categoryPath: string, elementName: string): Attribute[] {
        const categoryDescriptor = findDescriptorByPath(categoryPath);
        if (!categoryDescriptor) {
            return [];
        }
        const elementDescriptor = categoryDescriptor.elements[elementName];
        if (!elementDescriptor || !elementDescriptor.path) {
            return [];
        }
        return parseJsonFile<AttributeDescriptor[]>(elementDescriptor.path).map(attrInfo => {
            const attr = new Attribute();
            attr.name = attrInfo.name;
            attr.description = attrInfo.description;
            attr.type = attrInfo.type;
            attr.value = attrInfo.value != null ? convertAttrValue(attrInfo.type, attrInfo.value) : null;
            return attr;
        });
    }
```

2. in vRO run:
```js
const c = Server.createConfigurationElement('dummy', 'dummy')
System.log(typeof c.attributes)
System.log(c.attributes)
System.log(c.attributes === null)
```

Output:
```
2023-05-29 17:06:32.080 +02:00INFO(nl.rabobank.test/remco) object
2023-05-29 17:06:32.081 +02:00INFO(nl.rabobank.test/remco) null
2023-05-29 17:06:32.082 +02:00INFO(nl.rabobank.test/remco) true
```

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:**

mocking to return null when no attributes are present in a configuration element.

**Actual behavior:**

Mocking returns []

**Reproduces how often:** 100%

**Component/s:**

- typescript/vro-scripting-api/src/configurations.ts 
- typescript/vro-scripting-api/src/api/ConfigurationElementCategory.ts

**Affects Build/s:** 2.32.0

#### Client

-   Build Tools for VMware Aria Version: 2.23.0
-   Visual Studio Code Version: latest
-   OS Version: 

#### Server

-   vRealize Automation Version: 8.12
-   vRealize Orchestrator Version: 8.12
-   vRealize Operations Version: n/a
-   vRealize Log Insight Version: n/a

### Related issues and PRs

n/a

### Additional Context

n/a

**Comment by Michaelpalacce** [comment]
Should be fixed

**Comment by pe1pip** [comment]
@Michaelpalacce it seems you actually broke more than you fixed. Following test (demo.test.ts) works as expected in 2.33.0, but throws in 2.34.0:

```ts
function getConfigurationElementByPath (path: string, name: string): ConfigurationElement {
  const configurationElementCategory = Server.getConfigurationElementCategoryWithPath(path)
  const configurationElements = configurationElementCategory.allConfigurationElements

  const configurationElement = configurationElements.filter(function (configurationElement) {
    return configurationElement.name === name
  })

  if (configurationElement.length !== 1) {
    throw new Error('too many or zero matches')
  }
  return configurationElement[0]
}

function demo (): string {
  const environment = getConfigurationElementByPath('web-root', 'Environment')
  return `demo${environment.getAttributeWithKey('demo').value as string}`
}

describe('networkService test', () => {
  beforeEach(() => {
    const envCfg = Server.createConfigurationElement('web-root', 'Environment')
    envCfg.setAttributeWithKey('demo', 'Mock', 'string')
  })
  afterEach(() => {
    Server.removeConfigurationElementCategory(Server.getConfigurationElementCategoryWithPath('web-root')) // cleanup all cfgElements
  })
  it('x', () => {
    expect(demo()).toBe('demoMock')
  })
})
```

expected behaviour is `environment.getAttributeWithKey('demo').value` to equal 'Mock', but `environment.getAttributeWithKey()` returns null, even if the attribute exists.
