### ISSUE TITLE
Typescript: VcVirtualPCIPassthrough backing doesn't support VcVirtualPCIPassthroughVmiopBackingInfo

### ISSUE THREAD

**Issue by unbreakabl3** [vmware/build-tools-for-vmware-aria#111]
### Description

[Description of the issue. Affected functionality / feature.]

When trying to create / attache new PCI device (vGPU), the VcVirtualPCIPassthrough class doesn't support for VcVirtualPCIPassthroughVmiopBackingInfo.vgpu. The same code is working with pure JS.

```
...
spec.deviceChange[0].device = new VcVirtualPCIPassthrough()
spec.deviceChange[0].device.deviceInfo = new VcDescription()
spec.deviceChange[0].device.deviceInfo.summary = ''
spec.deviceChange[0].device.deviceInfo.label = 'New PCI device'
spec.deviceChange[0].device.backing = new VcVirtualPCIPassthroughVmiopBackingInfo()
spec.deviceChange[0].device.backing.vgpu = vGPUProfile
```
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/13556249/3e001ef0-610f-4f13-af6c-ae5ea1fa3b0a)

The suggested solution was that the `backing:` should accept both `VcVirtualDeviceBackingInfo | VcVirtualPCIPassthroughVmiopBackingInfo`

### Steps to Reproduce

1. create new VcVirtualMachineConfigSpec()
2. update relevant properties
3. viscode intellisense will complain 

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]
 2.32.0

#### Client

-   Build Tools for VMware Aria Version:  2.32.0
-   Visual Studio Code Version: 1.78.2
-   OS Version: 13.4

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version: 8.12.0
-   vRealize Operations Version:
-   vRealize Log Insight Version:

**Comment by unbreakabl3** [comment]
> 
Sure. Please.
 Stopped in a debug mode after the line 
 `spec.deviceChange[0].device.backing = new VcVirtualPCIPassthroughVmiopBackingInfo();`
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/13556249/6f78227a-cf9d-448e-8e1a-1140b33ef7bd)

**Comment by Michaelpalacce** [comment]
Backing seems to be null... weird. And you claim that it works if you pass VcVirtualPCIPassthroughVmiopBackingInfo ? I mean javascript won't complain but does it actually do anything? According to the API Explorer it shouldn't be accepted. Can you provide proof that it works and we can triage on this internally

**Comment by Michaelpalacce** [comment]
Merged
