### ISSUE TITLE
vro:pull - allow custom indentation to be used instead of the default 4 spaces

### ISSUE THREAD

**Issue by simplygeekuk** [vmware/build-tools-for-vmware-aria#125]
I am not sure if this is already supported but I am working in an environment where the indentation has been standardized on 2 spaces. Is there a way to allow vro:pull do honor the same indentation? Currently, after a vro:pull, I have to change the indentation of the pulled-down code.

**Comment by Michaelpalacce** [comment]
Hey @simplygeekuk this is currently not supported. It's also not something we want to do and is not really part of our roadmap, however if you do wish to see this, you can implement it and submit a pr for review
