### ISSUE TITLE
Build error when pushing on vRA 8.x

### ISSUE THREAD

**Issue by krasimirr** [vmware/build-tools-for-vmware-aria#157]
### Description

When pushing vRA 8.x project we get the following error:

[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.34.0:push (default-cli) on project new: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.34.0:push failed: Error executing POST to server: java.lang.ClassCastException : class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonNull and com.google.gson.JsonObject are in unnamed module of loader org.codehaus.plexus.classworlds.realm.ClassRealm @63062eea)

### Steps to Reproduce

1. Create vRA 8.x project
2. Push the project: mvn clean package vrealize:push -Penv

**Expected behavior:**
To successfully push the project.

**Actual behavior:**
Build Failure
**Reproduces how often:**
100%
**Component/s:**
common/artifact-manager

#### Client

-   Build Tools for VMware Aria Version: 2.34.0
-   Visual Studio Code Version: N/A
-   OS Version: Windows & MacOS

#### Server

-   vRealize Automation Version: N/A
-   vRealize Orchestrator Version: N/A
-   vRealize Operations Version: N/A
-   vRealize Log Insight Version: N/A

### Failure Logs

![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/13766883/c88ef9bf-713c-4c53-b628-98b9378f8348)

**Comment by VenelinBakalov** [comment]
@krasimirr are you still working on this one? Are there any specific steps needed to reproduce this as I am currently pushing successfully vRA 8 projects?
@Michaelpalacce do you know if this is related to some specific environment or bug which was already fixed?

**Comment by VenelinBakalov** [comment]
With the latest release, creating a new project from the following archetype results in a successful push:
https://github.com/vmware/build-tools-for-vmware-aria/blob/main/maven/archetypes/vra-ng/create.sh

**Comment by VenelinBakalov** [comment]
Mixed archetype also seems to push successfully (https://github.com/vmware/build-tools-for-vmware-aria/blob/main/maven/archetypes/ts-vra-ng/create.sh)

**Comment by VenelinBakalov** [comment]
It seems the issue is no longer present, I am not able to reproduce it on Mac OS with the 2 archetypes above. Closing for now, @krasimirr feel free to re-open if you find it still present.

**Comment by Michaelpalacce** [comment]
@VenelinBakalov I will reopen this. @krasimirr encountered this error with some specific data, lets wait for more details, he was testing it before the holidays

**Comment by VenelinBakalov** [comment]
Sure thing, let's see what is happening next week

**Comment by VenelinBakalov** [comment]
@krasimirr reminder to check if this is still valid

**Comment by VenelinBakalov** [comment]
@krasimirr @Michaelpalacce I see this one was auto closed, do you think it is still valid?
