### ISSUE TITLE
Automatically Generate Release Notes

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#160]
### Description

Investigate what's the best way to generate release notes.

### Additional Context

Some options

- https://github.com/release-drafter/release-drafter
- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by Hristo-Cholakov** [comment]
`name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if conventional-changelog-cli is installed
        id: check-install
        run: |
          if ! command -v conventional-changelog &> /dev/null; then
            echo "conventional-changelog-cli is not installed."
            echo "Installing it now..."
            npm install -g conventional-changelog-cli
          else
            echo "conventional-changelog-cli is already installed."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate Release Notes
        if: steps.check-install.outcome == 'success'
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push changes
        if: steps.check-install.outcome == 'success'
        run: |
          git config --global user.email "svc-wwcoe-ci-admin@vmware.com"
          git config --global user.name "WWCoE CI admin"
          git add CHANGELOG.md
          git commit -m "chore(release): Update changelog [skip ci]"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
`

**Comment by Hristo-Cholakov** [comment]
```
name: Generate Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if conventional-changelog-cli is installed
        id: check-install
        run: |
          if ! command -v conventional-changelog &> /dev/null; then
            echo "conventional-changelog-cli is not installed."
            echo "Installing it now..."
            npm install -g conventional-changelog-cli
          else
            echo "conventional-changelog-cli is already installed."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Generate Release Notes
        if: steps.check-install.outcome == 'success'
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push changes
        if: steps.check-install.outcome == 'success'
        run: |
          git config --global user.email "svc-wwcoe-ci-admin@vmware.com"
          git config --global user.name "WWCoE CI admin"
          git add CHANGELOG.md
          git commit -m "chore(release): Update changelog [skip ci]"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
```

**Comment by Michaelpalacce** [comment]
@VenelinBakalov do you think this is still a priority?

**Comment by VenelinBakalov** [comment]
@Michaelpalacce I wouldn't say priority, but I think it is still a topic of interest.

**Comment by Michaelpalacce** [comment]
I am not sure how to test this honestly 😄

**Comment by VenelinBakalov** [comment]
well...I can suggest one not pretty but working method...in prod kinda.
Commit a Workflow that has just the name and the following property:

name: <smth>

on:
  workflow_dispatch:

https://github.com/vmware/build-tools-for-vmware-aria/blob/main/.github/workflows/stale.yml

Once this is in master, the workflow_dispatch will enable you to select the action and run it manually. You can then create a branch with the code suggested by @Hristo-Cholakov and then you can manually run the workflow from that branch:
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/22296648/335ddf70-8fb0-4c48-8440-9782f9f7f4cc)

**Comment by VenelinBakalov** [comment]
Issue is still valid

**Comment by VenelinBakalov** [comment]
Still valid

**Comment by VenelinBakalov** [comment]
Not stale

**Comment by VenelinBakalov** [comment]
Decided approach is to no longer use CHANGELOG.md and rely only on release notes which will be auto generated by release drafter (https://github.com/release-drafter/release-drafter) and fine tuned during the actual release.
Re-opening for minor adjustments.

**Comment by VenelinBakalov** [comment]
Changelog archived and documentation templates updated
https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/archive/CHANGELOG.md
