### ISSUE TITLE
Create a minimal infrastructure template

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#162]
### Description

- We are aiming to create a minimal infra example with the help of containers
- Create a docker-compose file with
  - Sonatype Nexus
  - Gitlab CE
  - Gitlab Runner (JDK17, Node14, mvn 3.9.x)
  - Nginx for better navigation
- There are existing resources already present in the `infrastructure` folder that need to be updated
- Guides should be added on how the systems integrate with each other

**Comment by VenelinBakalov** [comment]
Requirement is still active, adding comment to remove stale state

**Comment by VenelinBakalov** [comment]
Requirement is still active, adding comment to remove stale state

**Comment by VenelinBakalov** [comment]
Still valid and ongoing topic

**Comment by deyan-r** [comment]
I started, but had to jump to another task, so now not working on it.

**Comment by VenelinBakalov** [comment]
Oks, for now we don't have anyone else assigned so in case you have any free availability and want to continue investigating, just know that it is still free
