### ISSUE TITLE
Unable to Pull vRO Content Sources or Catalog Items

### ISSUE THREAD

**Issue by RV1959** [vmware/build-tools-for-vmware-aria#168]
### Description

We have several Content Sources that we want to Pull and then Push to other vRA instances.
I have managed to get the Pull working for a Cloud Template Catalog Item.
However it does not work for vRO Content. 

Here is the content.yaml:

blueprint: 
  - GI machines
subscription: []
flavor-mapping: []
image-mapping: []
storage-profile: []
region-mapping: {}
catalog-item:
  - Cloud template sources__GI machines
  - vRO content ALGEMEEN projects__FileShare verwijderen
#  - vRO content SVCMT projects__Aanvraag niet-standaard wijziging
#  - vRO content UPLOAD projects__Upload IaaS template
custom-resource: []
resource-action: []
catalog-entitlement: []
content-source: 
  - Cloud template sources
#  - vRO content ALGEMEEN projects
#  - vRO content SVCMT projects
#  - vRO content UPLOAD projects
property-group: []
policy: {}

The GI Machines are correctly imported, but I get the following error on the vRO Content:

[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.31.1:pull (default-cli) on project CloudTemplateSources: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.31.1:pull failed: Catalog Item [FileShare verwijderen] not found for Source Name [vRO content ALGEMEEN projects] not found on the server. -> [Help 1]

I have additionally tried sharing the Catalog Item, FileShare verwijderen, with the project. Not sure if that is required?
It is visible in the GUI, but I still get this error.
Please advise.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce]

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

#### Client

-   Build Tools for VMware Aria Version: 2.31.1
-   Visual Studio Code Version: 1.77.0
-   OS Version: Windows 2016

#### Server

-   vRealize Automation Version: 8.11
-   vRealize Orchestrator Version: embedded
-   vRealize Operations Version:
-   vRealize Log Insight Version:

**Comment by abarajasca** [comment]
Hi @RV1959  , Issue tested in vRA 8.10, not able to reproduce same issue, but getting errors regards sharing policy that block run pull, 

```
[INFO] Currently exporting: VraNgContentSharingPolicyStore
[INFO] Nothing/null passed exporting everything
[ERROR] Error fetching content sharing policy
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.571 s
[INFO] Finished at: 2023-09-27T10:57:03-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.31.1:pull (default-cli) on project test_168: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.31.1:pull failed: org.springframework.web.client.HttpClientErrorException: 404 Not Found {"message":"No value present","statusCode":404,"errorCode":0}
```

Same issue in BTVA versions: 2.31.x,2.32.x,2.33, in versions: 2.34, 2.35, it works fine.

Tested in vRA 8.11, not able to reproduce the issue, all works fine.

Sharing policy is not required, only content source.  

content.yaml

```
blueprint:
  - GI machines
subscription: []
flavor-mapping: []  
image-mapping: []
storage-profile: []
region-mapping: {}
catalog-item: 
  - CT Sources__GI machines
  - VRO CS 1__Add a REST host
custom-resource: []
resource-action: []
catalog-entitlement: []
content-source: 
  - CT Sources
  - VRO CS 1
property-group: []
```

Try test in versions mentioned above and let me know your results/comments.

**Comment by RV1959** [comment]
Hi @abarajasca,
We have recently upgraded our Build Tools to 2.35.0, but we still get an error pulling the Content Source with vRO items:

[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.35.0:pull (default-cli) on
 project CloudTemplateSources: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugi
n:2.35.0:pull failed: Content Source [vRO content ALGEMEEN projects] not found on the server. -> [Help 1]

vRA still shows "vRealize Automation 8.11.1.29538 (21309636)", so do you have another idea where to look and solve our issue?
