### ISSUE TITLE
o11n-plugin-sql - SQLDatabaseManager.getDatabase definition to be removed

### ISSUE THREAD

**Issue by martinavel** [vmware/build-tools-for-vmware-aria#172]
### Description

In o11n-plugin-sql definition, the method SQLDatabaseManager.getDatabase must be removed since it is no longer presented in vRO API Explorer for vRA 7.6 and Aria 8.+.

Source: https://github.com/vmware/build-tools-for-vmware-aria/blob/main/vro-types/o11n-plugin-sql/index.d.ts

**Comment by VenelinBakalov** [comment]
Internal ticket https://jira.pscoe.vmware.com/browse/IAC-798
