### ISSUE TITLE
Failed to pull action

### ISSUE THREAD

**Issue by bjim** [vmware/build-tools-for-vmware-aria#174]
### Description

When pulling a package from vRO actions using the toolchain we receive the following error:

Error [ERROR] C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:651
[ERROR]     er = new Error(er)

### Steps to Reproduce

1. Import attached action into vRO
2. Run mvn commands to initialize the environment
3. Run mvn commands to push the package to vRO
4. Add the action to the package
5. Run the mvn comand to pull the package

**Preconditions:** [What are the preconditions to reproduce the issue]
Import the attached action

**Expected behavior:** [What you expect to happen]
The action should  exist in the action/src folder in vsCode

**Actual behavior:** [What actually happens]
It fails to import the action with the following error:
mvn vro:pull -Pdev-region1 -pl actions 
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<enabled>false</enabled>\u222b\n                    </... @114:23)  @ C:\Users\student3\.m2\settings.xml, line 114, column 23
[WARNING]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for starfleet.srm:team2_student3.actions:package:1.0.0-SNAPSHOT
[WARNING] 'parent.relativePath' of POM starfleet.srm:team2_student3.actions:1.0.0-SNAPSHOT (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\pom.xml) points at starfleet.srm:team2_student3-all instead of com.vmware.pscoe.o11n:actions-package, please verify your project structure @ line 5, column 11
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] 
[INFO] ----------------< starfleet.srm:team2_student3.actions >----------------
[INFO] Building team2_student3.actions 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] ------------------------------[ package ]-------------------------------
[INFO] 
[INFO] --- vro:2.35.1:pull (default-cli) @ team2_student3.actions ---
[INFO] Reading config for type : VRO
Oct 13, 2023 2:29:54 PM com.vmware.pscoe.iac.artifact.configuration.ConfigurationVro validate
INFO: Checking if exists refresh token
Oct 13, 2023 2:29:54 PM com.vmware.pscoe.iac.artifact.configuration.ConfigurationVro validate
INFO: Refresh token not detected using BASIC Authentication
[INFO] Refresh token not detected. Checking username and password on configuration
[INFO] Searching for Package Store for type VRO
[INFO] Detected ConfigurationVro
[WARNING] SSL: You are now ignoring certificate verification.
[WARNING] SSL: You are now ignoring hostname verification.
[INFO] Authentication strategy: 'VRA'
[INFO] Detecting vRO Server version '8.13.0.22124027'.
[INFO] Package | EXPORT | starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package
About to copy the file
C:\Users\student3\AppData\Local\Temp\3\vro-js-pull3569065046268057569\starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package
File copied.[INFO] Running vropkg... started
[INFO] 
[INFO] C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions>node "C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\bin\\..\dist\cli.js" --in flat --srcPath C:\Users\student3\AppData\Local\Temp\3\vro-js-pull3569065046268057569\starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package --out js --destPath C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions --privateKeyPEM target/archetype.keystore-2.0.1/private_key.pem --certificatesPEM target/archetype.keystore-2.0.1/cert.pem --keyPass VMware1! --version 1.0.0-SNAPSHOT --packaging package --artifactId team2_student3.actions --description "Build Tools for VMware Aria provides development and release management tools for implementing automation solutions            based on the VMware Aria Suite and VMware Cloud Director. The solution enables Virtual Infrastructure Administrators and             Automation Developers to use standard DevOps practices for managing and deploying content." --groupId starfleet.srm
[INFO] info: Extracting package C:\Users\student3\AppData\Local\Temp\3\vro-js-pull3569065046268057569\starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package to "C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions" folder...
[INFO] data is not xml file
[INFO] data is not xml file
[ERROR] C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:651
[ERROR]     er = new Error(er)
[ERROR]          ^
[ERROR]
[ERROR] Error: Non-whitespace before first tag.
[ERROR] Line: 0
[ERROR] Column: 1
[ERROR] Char: v
[ERROR]     at error (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:651:10)
[ERROR]     at strictFail (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:677:7)
[ERROR]     at beginWhiteSpace (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:951:7)
[ERROR]     at SAXParser.write (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:1006:11)
[ERROR]     at new XmlDocument (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\xmldoc\lib\xmldoc.js:301:19)       
[ERROR]     at exports.xml (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\util.js:13:25)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:65:27
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:4:12)
[ERROR]     at parseFlatElement (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:21:47)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:101:22
[ERROR]     at Array.map (<anonymous>)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:101:10
[ERROR]     at Generator.next (<anonymous>)
[ERROR]
[ERROR] Node.js v18.17.1
[INFO] Running vropkg... finished
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.171 s
[INFO] Finished at: 2023-10-13T14:29:58-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-actions-package-maven-plugin:2.35.1:pull (default-cli) on project team2_student3.actions: Running vropkg... failed with code 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Reproduces how often:** [What percentage of the time does it reproduce]
Every time

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]
mvn pull

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]
2.35.1, 2.34.0
### Environment
Windows 
vRO 8.12

#### Client

-   Build Tools for VMware Aria Version: 2.35.1
-   Visual Studio Code Version:1.82.2
-   OS Version:Windows 10

#### Server

-   vRealize Automation Version: 8.12
-   vRealize Orchestrator Version: 8.12
-   vRealize Operations Version: 
-   vRealize Log Insight Version:

### Failure Logs
mvn vro:pull -Pdev-region1 -pl actions 
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] expected START_TAG or END_TAG not TEXT (position: TEXT seen ...<enabled>false</enabled>\u222b\n                    </... @114:23)  @ C:\Users\student3\.m2\settings.xml, line 114, column 23
[WARNING]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for starfleet.srm:team2_student3.actions:package:1.0.0-SNAPSHOT
[WARNING] 'parent.relativePath' of POM starfleet.srm:team2_student3.actions:1.0.0-SNAPSHOT (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\pom.xml) points at starfleet.srm:team2_student3-all instead of com.vmware.pscoe.o11n:actions-package, please verify your project structure @ line 5, column 11
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO] 
[INFO] ----------------< starfleet.srm:team2_student3.actions >----------------
[INFO] Building team2_student3.actions 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] ------------------------------[ package ]-------------------------------
[INFO] 
[INFO] --- vro:2.35.1:pull (default-cli) @ team2_student3.actions ---
[INFO] Reading config for type : VRO
Oct 13, 2023 2:29:54 PM com.vmware.pscoe.iac.artifact.configuration.ConfigurationVro validate
INFO: Checking if exists refresh token
Oct 13, 2023 2:29:54 PM com.vmware.pscoe.iac.artifact.configuration.ConfigurationVro validate
INFO: Refresh token not detected using BASIC Authentication
[INFO] Refresh token not detected. Checking username and password on configuration
[INFO] Searching for Package Store for type VRO
[INFO] Detected ConfigurationVro
[WARNING] SSL: You are now ignoring certificate verification.
[WARNING] SSL: You are now ignoring hostname verification.
[INFO] Authentication strategy: 'VRA'
[INFO] Detecting vRO Server version '8.13.0.22124027'.
[INFO] Package | EXPORT | starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package
About to copy the file
C:\Users\student3\AppData\Local\Temp\3\vro-js-pull3569065046268057569\starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package
File copied.[INFO] Running vropkg... started
[INFO] 
[INFO] C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions>node "C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\bin\\..\dist\cli.js" --in flat --srcPath C:\Users\student3\AppData\Local\Temp\3\vro-js-pull3569065046268057569\starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package --out js --destPath C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions --privateKeyPEM target/archetype.keystore-2.0.1/private_key.pem --certificatesPEM target/archetype.keystore-2.0.1/cert.pem --keyPass VMware1! --version 1.0.0-SNAPSHOT --packaging package --artifactId team2_student3.actions --description "Build Tools for VMware Aria provides development and release management tools for implementing automation solutions            based on the VMware Aria Suite and VMware Cloud Director. The solution enables Virtual Infrastructure Administrators and             Automation Developers to use standard DevOps practices for managing and deploying content." --groupId starfleet.srm
[INFO] info: Extracting package C:\Users\student3\AppData\Local\Temp\3\vro-js-pull3569065046268057569\starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.package to "C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions" folder...
[INFO] data is not xml file
[INFO] data is not xml file
[ERROR] C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:651
[ERROR]     er = new Error(er)
[ERROR]          ^
[ERROR]
[ERROR] Error: Non-whitespace before first tag.
[ERROR] Line: 0
[ERROR] Column: 1
[ERROR] Char: v
[ERROR]     at error (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:651:10)
[ERROR]     at strictFail (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:677:7)
[ERROR]     at beginWhiteSpace (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:951:7)
[ERROR]     at SAXParser.write (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:1006:11)
[ERROR]     at new XmlDocument (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\node_modules\xmldoc\lib\xmldoc.js:301:19)       
[ERROR]     at exports.xml (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\util.js:13:25)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:65:27
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:4:12)
[ERROR]     at parseFlatElement (C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:21:47)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:101:22
[ERROR]     at Array.map (<anonymous>)
[ERROR]     at C:\dev\team2\rp-science-ariaa8n\srm\team2_student3\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:101:10
[ERROR]     at Generator.next (<anonymous>)
[ERROR]
[ERROR] Node.js v18.17.1
[INFO] Running vropkg... finished
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.171 s
[INFO] Finished at: 2023-10-13T14:29:58-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-actions-package-maven-plugin:2.35.1:pull (default-cli) on project team2_student3.actions: Running vropkg... failed with code 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

### Additional Context
see attachment
[starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.zip](https://github.com/vmware/build-tools-for-vmware-aria/files/12899788/starfleet.srm.team2_student3.actions-1.0.0-SNAPSHOT.zip)

**Comment by edwardblackwell** [comment]
I've run into the same issue when it came to adding an existing workflow to the workflows package in vRO, and then tried to pull that project into my Maven workspace.  After experimenting a LOT with the content of the workflow, I found two pieces of code that triggered this behavior.  The first was when a for loop was set up to iterate over an array, but the forEach function built into every JavaScript array was not used.  Instead, the `for each` construct was.  Here's` an example:

`for each(var item in items) {`
`    System.log("Item:  " + item);`
`}`

instead of:

`items.forEach(function(item) {`
`    System.log("Item:  " + item};`
`);`

The second scenario I found that triggered the error was the use of the VcPlugin to retrieve objects from the vCenter instances configured within the vRA inventory like this:

`var matchingPortGroups = VcPlugin.getAllDistributedVirtualPortgroups(null, "xpath:name[matches(.,'" + networkName + "')]");`

I tried this line of code both with the xpath search string and without, but got the same error both ways.  As soon as I removed this line of code, and changed the for loops to use the forEach looping technique, the errors disappeared.  This doesn't mean I fixed the workflow so it could be pulled, as I needed that VcPlugin call, but it does highlight a couple of causes for the error.

**Comment by VenelinBakalov** [comment]
@bjim could you try to re-import the vRO package file - for some reason vRO doesn't recognise it and I cannot import it even if I rename to .package.

@edwardblackwell thanks for the feedback on those 2 issues. Could you test just the 2nd case (the vC plugin) isolated to see if it works for you? Build tools supports vC plugin usage and xpath and it should be working properly both in actions and workflows unless there is some unrecognised syntax but the sample above looks good to me.

Regarding the first sample with the `for each` - it is true, this is deprecated syntax and is currently not supported by Build Tools. In theory you should be able to PULL successfully but won't be able to build or push after that. The handling itself comes for an indirect opensource dependency of the project.

One easy workaround that can be used is that the specific element that contains this syntax can be added as part of XML based project and PULLED through that project - this will not block building the package later on, since the XML file wraps the code as a string and is not recognised as buildable code. I am leaving a test screenshot on how this can look like:
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/22296648/05010b51-0bb3-442a-a60d-e60fb25967e4)

Note that the sample is with a Workflow but Action can be included in an XML project and pulled as well.

**Comment by Michaelpalacce** [comment]
@bjim  @edwardblackwell any updates to this?

**Comment by VenelinBakalov** [comment]
Just FYI, `for each` syntax support was added in https://github.com/vmware/build-tools-for-vmware-aria/pull/366
And released with 2.41.0: https://github.com/vmware/build-tools-for-vmware-aria/releases/tag/v2.41.0
