### ISSUE TITLE
shim for Array.from() doesn't create copy without mapfn

### ISSUE THREAD

**Issue by pe1pip** [vmware/build-tools-for-vmware-aria#192]
### Description

Array.from() is supposed to create a (shallow) copy, the shim doesn't do that if no map function is provided. This is an issue if the caller expects the original array to be unmodified if elements are pushed to the copy.

### Steps to Reproduce

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:** [What you expect to happen]

A fix could be:

```ts
	static arrayFrom(arrayLike: ArrayLike<any>, mapfn?: (v: any, k: number) => any): any[] {
		let array: <any[]>

		if (mapfn) {
			array = arrayLike.map(mapfn);
		}  else {
			array = arrayLike.map(e => e);
                }

		return array;
	}
```

**Actual behavior:** [What actually happens]

```ts
	static arrayFrom(arrayLike: ArrayLike<any>, mapfn?: (v: any, k: number) => any): any[] {
		let array = <any[]>arrayLike;

		if (mapfn) {
			array = array.map(mapfn);
		}

		return array;
	}
```

**Reproduces how often:** [What percentage of the time does it reproduce]

100%

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]

```packages/ecmascript/src/Shims.ts```

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

All

#### Client

-   Build Tools for VMware Aria Version: n/a
-   Visual Studio Code Version: n/a
-   OS Version: n/a

#### Server

-   vRealize Automation Version: n/a
-   vRealize Orchestrator Version: n/a
-   vRealize Operations Version: n/a
-   vRealize Log Insight Version: n/a

**Comment by VenelinBakalov** [comment]
I found additional issues - implementation does not work properly when providing a mapping function and calling Array.from() for string, Map and Set. String is returned as string instead of array, the other 2 throw error because they cannot find map.

**Comment by VenelinBakalov** [comment]
Internal ticket: https://jira.pscoe.vmware.com/browse/IAC-803
