### ISSUE TITLE
vROPs default policy feature not working with version 2.36.0

### ISSUE THREAD

**Issue by abyabrahameaso** [vmware/build-tools-for-vmware-aria#195]
vROPs default policy feature has been introduced in 2.36.0, but this is not working.

vROPS Version: 8.12.1 (22481587)

Error during content pull:- 
vROps Pull Plugin: Executing in Project Base: "C:\Dev\Repo\cwd_vrops\vrops"
ject cwd_vrops.vrops: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vrops-package-maven-plugin:2.36.0:pull failed: Unable to load vROps Package Descriptor [C:\Dev\Repo\cwd_vrops\vrops\content.yaml]: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
[ERROR]  at [Source: (File); line: 59, column: 3] (through reference chain: com.vmware.pscoe.iac.artifact.model.vrops.VropsPackageDescriptor["default-policy"])

### Steps to Reproduce

1. add default-policy: in content.yaml and specify the default policy.
2. try to build\pull\push the package, above error appears.

**Reproduces how often:** Every time.
**Component/s:** vROPS

**Affects Build/s:** 2.36.0

#### Client

-   Build Tools for VMware Aria Version:
-   Visual Studio Code Version:
-   OS Version:

#### Server
-   vRealize Operations Version:  8.12.1 (22481587)

### Failure Logs
vROps Pull Plugin: Executing in Project Base: "C:\Dev\Repo\cwd_vrops\vrops"
ject cwd_vrops.vrops: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vrops-package-maven-plugin:2.36.0:pull failed: Unable to load vROps Package Descriptor [C:\Dev\Repo\cwd_vrops\vrops\content.yaml]: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
[ERROR]  at [Source: (File); line: 59, column: 3] (through reference chain: com.vmware.pscoe.iac.artifact.model.vrops.VropsPackageDescriptor["default-policy"])

**Comment by akantchev** [comment]
Hi @abyabrahameaso Please make sure that the policy configuration in the content.yaml has the following structure (indentation is important as well)
policy:
 - "Default Policy"
 - "NSX-T Security Configuration Guide"
 - "Foundation Policy"
default-policy: "NSX-T Security Configuration Guide"

**Comment by abyabrahameaso** [comment]
@akantchev Thanks for the clarity. That helped and it works now.
