### ISSUE TITLE
Catalog Item (vRO workflow) Description not getting updated on the existing catalog item

### ISSUE THREAD

**Issue by vivekmandal** [vmware/build-tools-for-vmware-aria#197]
### Description

During The Content Push, If the Catalog Item (vRO workflow) already existing having some description, It would not be updated with the new vRO Workflow Description. This was working in the previous releases of vRBT (eg. 2.25.1).  Afterwards from one of the versions, it stopped working.

### Steps to Reproduce

1. Load the vRO workflows to vRA as catalog items with some workflow description.
2. Change the workflow description and try to load the item once again.
3. The catalog item would still have the old description on the UI.

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:**  Catalog Item should reflect the updated description of the workflow

**Actual behavior:** Catalog Item has the old workflow description shown on the UI.

**Reproduces how often:** Everytime.

**Affects Build/s:** 2.36.0

#### Client

-   Build Tools for VMware Aria Version: v2.36.0

#### Server

-   vRealize Automation Version: v8.10.1.26903 (20735161)

**Comment by Michaelpalacce** [comment]
@vivekmandal, we need some clarifications here. The description contradicts the title, so it's hard to understand what exactly is the problem. Can you try to edit the description? Furthermore, any screenshots are more than welcome

**Comment by vivekmandal** [comment]
@Michaelpalacce I am talking about the vRO Workflow Description which is also visible on the catalog item in vRA. Please Refer the below screenshots..
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/37260650/6dde602b-f4b9-4a15-b4c9-693e0f727c22)
![image](https://github.com/vmware/build-tools-for-vmware-aria/assets/37260650/6c742094-34c7-4a45-9b55-125fb090bbce)

**Comment by Michaelpalacce** [comment]
There is a data collection sync that needs to happen between Aria Automation and Aria Orchestrator. If you trigger that, does it get fixed?

**Comment by vivekmandal** [comment]
I tried doing that. waited for few hours too. But it did not help.

**Comment by vhagar91** [comment]
This looks like the same issue that with inputs if the workflow version remains the same aria will not update his references on the DB

**Comment by vivekmandal** [comment]
@vhagar91  Thanks for the hint. revising the version did help! :)

**Comment by vivekmandal** [comment]
Increasing the workflow version helped.
