### ISSUE TITLE
TS Workflow is missing the ability to set variable's value

### ISSUE THREAD

**Issue by unbreakabl3** [vmware/build-tools-for-vmware-aria#20]
### Description

Currently, the Typescript WFs are supporting only variable name and type to be created. There is no option to provide a variable's value and/or description. It can be very useful to have this ability. Without setting the variables, its almost not possible to create any workflow.

### Alternatives

No

### Additional Context

This problem was discussed in the vRBT Slack channel.

**Comment by Michaelpalacce** [comment]
@unbreakabl3 can you fetch a wf as XML and post a comment with what the xml looks like in regards to attributes. 

I'm interested in all the possible fields. 

For this purpose you can create different attributes, some with values, some with more complex values, descriptions, etc

**Comment by pe1pip** [comment]
I would suggest using the workflow only to call an action that does the actual work. The workflow just has inputs and outputs, but no need for variables. In that action you can then define any variable you need. Also, this gives you the ability to use the unit testing framework on that action.

**Comment by unbreakabl3** [comment]
True. Thanks for your valuable comment.
