### ISSUE TITLE
Conditional Execution in Saga

### ISSUE THREAD

**Issue by krasimirr** [vmware/build-tools-for-vmware-aria#206]
### Description
Currently there are cases when some tasks/workflows need to be executed conditionally. It would be beneficial if functionality is implemented that calls those tasks/workflows only if a condition is matched based on a saga state value.

Example:
```xml
tasks:
   StageOne:
       execute: testSagaTask
       if: conditionVariable # Newly intoduced variable
```

### Additional Context
This enhancement will take place in saga.ts.

- Actions - adding a conditional check, based on the **conditionVariable**, whether to execute the script or not
- Workflows - the most suitable solution for when we have **if: conditionVariable** would be to wrap them in scriptable tasks, and execute them using **AsyncWorkflowExecutor** based on the **conditionVariable**. For workflows without **if: conditionVariable**, the same logic will be applied as before -> building a workflow element, thus there won't be any impact on existing behaviour.

**Comment by VenelinBakalov** [comment]
@krasimirr do you still intend to work on this issue?

**Comment by VenelinBakalov** [comment]
Synced with Krasimir, the task is currently in progress

**Comment by Michaelpalacce** [comment]
Finished

**Comment by VenelinBakalov** [comment]
Since this is implemented and merged I am removing the `Stale` label which is leftover
