### ISSUE TITLE
ABX content export is not working with Java 17

### ISSUE THREAD

**Issue by vsuddya** [vmware/build-tools-for-vmware-aria#219]
### Description
ABX content export is not working with Java 17. Working as expected with earlier version (tested with Java 7).

### Steps to Reproduce

1. Create ABX [project](https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/archive/doc/markdown/use-workstation-abx-project.md)
2. Check java version with command `java -version`
3. Deploy ABX content with command `mvn package vrealize:push -Pcorp-env`

**Expected behavior:** 
ABX content successfully deployed

**Actual behavior:** 
Deployment failure

**Reproduces how often:** 
100%

**Component/s:** 
common/artifact-manager

#### Client

-   Build Tools for VMware Aria Version: 2.36.0

#### Server

-   vRealize Automation Version: 8.9

### Failure Logs
![Screenshot 2024-01-12 at 15 56 06](https://github.com/vmware/build-tools-for-vmware-aria/assets/127217826/fce51b98-b795-4899-8f28-43ea704fcdd2)

**Comment by vsuddya** [comment]
https://github.com/google/gson/issues/1979

**Comment by VenelinBakalov** [comment]
Validated with the latest fix: https://github.com/vmware/build-tools-for-vmware-aria/pull/569
