### ISSUE TITLE
ABX project templates must be updated

### ISSUE THREAD

**Issue by vsuddya** [vmware/build-tools-for-vmware-aria#220]
### Description
Recently were introduced new parameters: 

- memoryLimitMb
- timeoutSec
- inputSecrets
- inputConstants
- provider
etc

[ABX project](https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/archive/doc/markdown/use-workstation-abx-project.md) templates must be updated to ensure consistency.

**Comment by mtopchieva** [comment]
The abx project template is updated. But an improvement can be made, so that the 'runtime' property is populated with the correct value taken from the 'mvn archetype:generate' command's runtime input (nodejs/python/powershell).

**Comment by VenelinBakalov** [comment]
@mtopchieva do you think you will have availability to check back on this task once you finish with your ongoing task?
Also, could you add as a comment here the PR which is adding the template update

**Comment by mtopchieva** [comment]
Hi @VenelinBakalov, unfortunately I will not manage to work on the issue in the forthcoming 2 weeks at least. There is not an open PR because the implementation is not complete.

**Comment by VenelinBakalov** [comment]
Still active, there is PR opened

**Comment by VenelinBakalov** [comment]
@mtopchieva I saw you had a suggestion for improvement in the comments above. If this is still a possible improvement, could you open a github issue with the suggestion here: https://github.com/vmware/build-tools-for-vmware-aria/issues
