### ISSUE TITLE
Error Pushing vRA Content after Updating to 2.37.0 

### ISSUE THREAD

**Issue by oporanski** [vmware/build-tools-for-vmware-aria#232]
### Description

Error Pushing vRA Content after Updating to 2.37.0. After downgrading back to 2.36.0 push is ok (no vRA restart, no services restart)
Source vRA 8.16
Destination vRA 8.14.0

12:12:04.974 [main] INFO  com.vmware.pscoe.iac.artifact.VraPackageStore - Searching for Package Store for type VRANG
12:12:04.976 [main] INFO  com.vmware.pscoe.iac.artifact.VraPackageStore - Detected ConfigurationVroNg
12:12:05.078 [main] WARN  com.vmware.pscoe.iac.artifact.rest.RestClientFactory - SSL: You are now ignoring certificate verification.
12:12:05.078 [main] WARN  com.vmware.pscoe.iac.artifact.rest.RestClientFactory - SSL: You are now ignoring hostname verification.
12:12:05.222 [main] INFO  com.vmware.pscoe.iac.artifact.rest.RestClientVraNgAuthNInterceptor - Request URL: https://cloud.xxx.internal.xxx-group.net/vco/api/about
12:12:05.222 [main] INFO  com.vmware.pscoe.iac.artifact.rest.RestClientVraNgAuthNInterceptor - Acquiring refresh token with credentials
12:12:05.227 [main] INFO  com.vmware.pscoe.iac.artifact.rest.RestClientVraNgAuthNInterceptor - Auth URL: [https://cloud.xxx.internal.xxx-group.net:443/csp/gateway/am/api/login?access_token](https://cloud.xxx.internal.xxx-group.net/csp/gateway/am/api/login?access_token)
xxxx12:12:06.753 [main] INFO  com.vmware.pscoe.iac.artifact.VraPackageStore - Detecting vRO Server version '8.14.0.22610007'.
12:12:06.762 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Start executing import all packages...
12:12:06.810 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.activedirectory-2.0.16.package
12:12:09.594 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.class-2.4.7.package
12:12:10.328 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.fs-1.1.1.package
12:12:11.437 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.guestops.actions-1.2.6.package
12:12:12.651 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.guestops-1.2.6.package
12:12:13.653 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.locking-1.0.1.package
12:12:14.669 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.logging-3.3.1.package
12:12:17.702 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.rest-template-2.5.7.package
12:12:19.096 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.templates-2.0.3.package
12:12:19.888 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.util.wfs-1.0.2.package
12:12:20.729 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.util-2.19.6.package
12:12:28.962 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.validator-2.0.3.package
12:12:29.882 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.vmware.pscoe.library.vc-1.4.3.package
12:12:33.621 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.xxx.di-1.1.3.package
12:13:36.606 [main] INFO  com.vmware.pscoe.iac.artifact.VroPackageStore - Package | IMPORT | com.xxx.di.actions-1.1.3.package
Exception in thread "main" org.springframework.web.client.HttpClientErrorException: 502 Invalid/Unreachable FQDN or IP address
	at com.vmware.pscoe.iac.artifact.rest.RestClientFactory$1.handleError(RestClientFactory.java:190)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:709)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:662)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:637)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:558)
	at com.vmware.pscoe.iac.artifact.rest.RestClientVro.importPackageForce(RestClientVro.java:294)
	at com.vmware.pscoe.iac.artifact.rest.RestClientVro.importPackageWithMerge(RestClientVro.java:255)
	at com.vmware.pscoe.iac.artifact.rest.RestClientVro.importPackage(RestClientVro.java:303)
	at com.vmware.pscoe.iac.artifact.VroPackageStore.importPackage(VroPackageStore.java:293)
	at com.vmware.pscoe.iac.artifact.VroPackageStore.importAllPackages(VroPackageStore.java:225)
	at com.vmware.pscoe.iac.artifact.VroPackageStore.importAllPackages(VroPackageStore.java:137)
	at com.vmware.pscoe.iac.installer.Installer.main(Installer.java:930)

### Steps to Reproduce

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:** [What you expect to happen]
successful jenkins build 

**Actual behavior:** [What actually happens]
Generic Error: 502 Invalid/Unreachable FQDN or IP address

**Reproduces how often:** [What percentage of the time does it reproduce]
100% rerun the pipeline 5 times with different packages versions 

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]
    <modules>
        <module>actions</module> - JS Project 
        <module>workflows</module> - XML Project 
        <module>vra</module> - vra-ng
        <module>codestream</module> - Codestream project
  </modules>

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

#### Server

-   vRealize Automation Version: 8.14.0
-   vRealize Orchestrator Version: 8.14.0 (internal)
-   vRealize Operations Version: NA
-   vRealize Log Insight Version: NA

### Failure Logs
Above

**Comment by Michaelpalacce** [comment]
@akumanov-vmw  can you take a look
Think this was introduced here:

https://github.com/vmware/build-tools-for-vmware-aria/pull/221

**Comment by akumanov-vmw** [comment]
Hi @oporanski, thanks for this one, the status code is 502 which means bad gateway and probably cannot reach to the vra. Could you, please, validate whether you have connection to the vra? Do you have proxy? Are you using environment.properties file and if yes is it the correct FQDN inside or IP address?
Thanks in advance.

**Comment by oporanski** [comment]
Just reverting the package version in all pom.xml files back to 2.36.0 fixed the issue 
I did not restart the vRA or vRA Services

**Comment by oporanski** [comment]
> @akumanov-vmw can you take a look Think this was introduced here:
> 
> #221

this is response 404 i got 502 Invalid/Unreachable

**Comment by oporanski** [comment]
This was w production push i can retry over a weekend
