### ISSUE TITLE
Object.setPrototypeOf() method is missing / not transpiled correctly

### ISSUE THREAD

**Issue by pe1pip** [vmware/build-tools-for-vmware-aria#264]
### Description

I want to extend the Error class. Apparently the transpilation of the code is incorrect:

```ts
export class NsxtError extends Error {
  public readonly cause: ErrorCause
  constructor (p: string, m: string, cause: ErrorCause) {
    super(`${p}${m}`)
    Object.setPrototypeOf(this, new.target.prototype) // restore this object
    this.cause = cause
  }
}
```

Is transpiled to:

```js
    var NsxtError = /** @class */ (function (_super) {
        tslib_1.__extends(NsxtError, _super);
        function NsxtError(p, m, cause) {
            var _newTarget = this.constructor;
            var _this = _super.call(this, "" + p + m) || this;
            Object.setPrototypeOf(_this, _newTarget.prototype); // restore this object
            _this.cause = cause;
            return _this;
        }
        return NsxtError;
    }(Error));
```

and it should be:

```js
    var NsxtError = /** @class */ (function (_super) {
        tslib_1.__extends(NsxtError, _super);
        function NsxtError(p, m, cause) {
            var _newTarget = this.constructor;
            var _this = _super.call(this, "" + p + m) || this;
            _this.__proto__ = _newTarget.prototype
            _this.cause = cause;
            return _this;
        }
        return NsxtError;
    }(Error));
```

### Alternatives

don't know.

### Additional Context

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-2.html#support-for-newtarget

**Comment by pe1pip** [comment]
would be nice if somebody could look at this

**Comment by VenelinBakalov** [comment]
Hi @pe1pip , could you share what issue or error you are encountering in vRO with this setup? It should be possible to extend the error object without an issue. Do you need to explicitly call the "Object.setPrototypeOf" function?
Here is one sample of error inheritance:

```
export class MissingObjectError extends Error {
    constructor(name: string, entityType: string) {
        const message = "Entity with name '" + name + "' not found in vCenter.";
        super(message);
        this.name = MissingObjectError.name;
    }
}
```

**Comment by VenelinBakalov** [comment]
I am not sure in this case of inheritance whether you will really need the Object.setPrototypeOf() call but we should be able to extend and add this function.

**Comment by pe1pip** [comment]
the problem arises if you want additional properties in the Error object, in this case the `cause` property:

```ts
export class NsxtError extends Error {
  public readonly cause: ErrorCause
  constructor (p: string, m: string, cause: ErrorCause) {
    super(`${p}${m}`)
    Object.setPrototypeOf(this, new.target.prototype) // restore this object
    this.cause = cause
  }
}
```

**Comment by VenelinBakalov** [comment]
Interesting..in theory "extends" keyword should be enough. However, in my tests I found that without Object.setPrototypeOf() everything seems to work for the error but if you log err.constructor.name it logs "Error". But if you add the setPrototypeOf() call as in your sample err.constructor.name will log NsxtError.

I think I managed to get it running at least with a simple test. If everything is ok I will open a PR tomorrow but it would be great to double check on your side as well

**Comment by pe1pip** [comment]
This is a well documented 'feature' of typescript, see for example: https://stackoverflow.com/questions/41102060/typescript-extending-error-class and https://github.com/microsoft/TypeScript-wiki/blob/7adbad944469a2943c1ba2032a1fb1735b89a8f3/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work (I had to go a bit back in history of that file). So, until Mozilla Rhino/Orchestrator gets 'https://mozilla.github.io/rhino/compat/engines.html#ES2015-functions-arrow-functions-lexical--new-target--binding' fixed we have this issue.

**Comment by VenelinBakalov** [comment]
@pe1pip whenever you have time could you check and possibly test on your side as well: https://github.com/vmware/build-tools-for-vmware-aria/pull/277/files

**Comment by pe1pip** [comment]
Hi @VenelinBakalov , I have a build error in vropkg, this is probably something in my environment, but I have no time to investigate. The PR looks quite ok, so I have little doubt that it works.

**Comment by VenelinBakalov** [comment]
Got it, thanks for pointing out this issue and adding the related documentation links, that was really helpful!
