### ISSUE TITLE
JSDoc parsing improvement

### ISSUE THREAD

**Issue by pe1pip** [vmware/build-tools-for-vmware-aria#278]
### Description

Currently the build tools JSDoc syntax @param and @returns for array types is {Array/string}, it would be nice if the packager would accept the {string[]} notation and transform that to Array/string. This would allow us to ESlint the JSDoc completely with type checking.

Secondly, the order of the @param statements must match the order of the arguments in the function declaration, otherwise the params will get mixed up.

### Alternatives

For typescript files, the JSDoc is redundant, all types are specified in the function declaration. Getting the types from the function declaration would be even less error prone. The JSDoc would then be ignored completely.

### Additional Context

Runtime error and ESlint warning/error:
```ts
/*
 * @param {string} b -
 * @param {string} a -
 * @returns {Array/string}
 */
(function (a: string, b: string): string[] {
  return [a, b]
)
```

Eslint warning:
```ts
/**
 * @returns {Array/string}
 */
(function (): string[] {
  return ['a', 'b']
)
```

Better:
```ts
/**
 * @returns {string[]}
 */
(function (): string[] {
  return ['a', 'b']
)
```

Ideal:
```ts
/**
 * ignored jsdoc in typescript
 */
(function (): string[] {
  return ['a', 'b']
)
```

**Comment by Michaelpalacce** [comment]
Hey @pe1pip 

So, regarding parsing typescript, that will be really hard to do as the parsing of JSdoc actually happens in vropkg, not vrotsc (typescript compiler).

However reagrding the other 2, we need to change the logic in 

`getParamsFromJavascriptDoc`/`getReturnStatementFromJavascriptDoc`/`parseType` in `typescript/vropkg/src/parse/js.ts` to accomodate this. We need to also be backwards compatible. 

I like the `Better` option if you ask me.

**Comment by Michaelpalacce** [comment]
```js
/**
 * @param {string} test
 * @param {Test[]} param
 * @param {Array/string} opt
 *
 * @returns {string[]}
 */
(function(test, param, opt): string[] {
	return ['a', 'b'];
});
```

transforms to:

```xml
<dunes-script-module name="example" result-type="Array/string" api-version="6.0.0" id="49e956dd-b31b-4c8d-9137-e43391d0dc9e" version="1.0.1" allowed-operations="vef"><description/><param n="test" t="string"/><param n="param" t="Array/Test"/><param n="opt" t="Array/string"/><script encoded="false"><![CDATA[return ['a', 'b'];]]></script></dunes-script-module>

```

**Comment by VenelinBakalov** [comment]
@pe1pip FYI https://github.com/vmware/build-tools-for-vmware-aria/pull/284/files?diff=unified&w=1

**Comment by VenelinBakalov** [comment]
Closed with https://github.com/vmware/build-tools-for-vmware-aria/pull/284
@pe1pip FYI, we are planning a release today so this feature should be out soon

**Comment by pe1pip** [comment]
@Michaelpalacce @VenelinBakalov  thanks, looking forward to using this
