### ISSUE TITLE
Workflow Decorators with the ability to define more canvas items

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#289]
### Description

Aria Orchestrator's workflows have: 
<img width="239" alt="image" src="https://github.com/vmware/build-tools-for-vmware-aria/assets/17056014/3ccd2465-f009-4be7-b09f-40f8b74c39aa">

From these we only support "Scriptable task"s. We could think about a wider support for some low-hanging fruits and easier to implement canvas items. After building a base, we can expand in the future with wider support for more items.

> A feature like this would be really useful in cases where for example we want to use waiting timers or user interactions. These items are more resource efficient than just a normal sleep (for the waiting timer) and well, the interaction is not currently supported.

A mock example is provided:

```ts
@Workflow({
	name: "Example Waiting Timer",
	path: "VMware/PSCoE",
	attributes: {
		waitingTimer: {
			type: "Date"
		}
	}
})
export class HandleNetworkConfigurationBackup {
	@Item({
		target = "decisionElement",
		// Potentially, don't do this.
		exception = ""
	})
	public execute(
		@Out @In waitingTimer: Date
	) : void {
		// Some logic here to create a conditional waitingTimer
		const tt = Date.now() * 1000;
		waitingTimer = new Date(tt);
	}

	@DecisionItem({
		target: "waitingForEvent",
		// null would mean exit
		else: null
	})
	public decisionElement(){
		return (waitingTimer !== null);
	}

	@WaitingTimerItem({
		target = "execute"
	})
	public waitForEvent(waitingTimer: Date) {
	}
}
```

Note:
- This should be backwards compatible

**Comment by VenelinBakalov** [comment]
@Michaelpalacce should we close this or we want to keep it open for support for other elements?

**Comment by Michaelpalacce** [comment]
I want to close it and I will open new ones

**Comment by unbreakabl3** [comment]
@Michaelpalacce, that is an amazing thing. Thank you for that 🙏🏻

**Comment by Michaelpalacce** [comment]
@unbreakabl3 hahaha no worries
