### ISSUE TITLE
The VcComputeResourceConfigSpec class is missing a few attributes

### ISSUE THREAD

**Issue by unbreakabl3** [vmware/build-tools-for-vmware-aria#297]
### Description

The VcComputeResourceConfigSpec class is missing a few attributes and types of those attributes

### Steps to Reproduce

1. Compare the class' attributes in vRBT with vRO API

**Preconditions:** N/A

**Expected behavior:** The attributes are exists

**Actual behavior:** The attributes are missing

**Reproduces how often:** Always

**Component/s:** "maven/plugins/o11n-plugin-vc"

**Affects Build/s:** 0.39.0

#### Client

-   Build Tools for VMware Aria Version: 0.39.0
-   Visual Studio Code Version: 1.90.2
-   OS Version: MacOS 13.4

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version: 8.17.0
-   vRealize Operations Version:
-   vRealize Log Insight Version:

**Comment by VenelinBakalov** [comment]
Closed in https://github.com/vmware/build-tools-for-vmware-aria/pull/298 by @unbreakabl3
