### ISSUE TITLE
vRA 7 Deprecation

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#306]
This is blocked by #305 

### Description

In light of VMware's support ending for vRA 7, the `vra` archetype should be removed or marked as deprecated.

All plugins, stores, logic related to it needs to be removed.

Possibly affected modules:

- `vrotsc`
- `vropkg`
- `artifact-manager`
- `maven`

**Comment by SimonSparksUK** [comment]
Please only mark this as deprecated, until June 2025.

**Comment by SimonSparksUK** [comment]
May I suggest that version 3.0.0 is the point at which vRA 7 / vRO 7 related items are removed.

**Comment by SimonSparksUK** [comment]
> > Please only mark this as deprecated, until June 2025.
> 
> Any Reason for this @SimonSparksUK?

We are in the process of a HUGE migration of a Service Provider from vRA v7.6 to Aria Suite v8.18 we are doing some very custom export of data from vRA v7.6 / import of VM into Aria Suite v8.18

**Comment by SimonSparksUK** [comment]
We are still developing new features e.g. we have implemented the new workflow items thing which was recently released to make incident troubleshooting easier for the 1st line guys

**Comment by Michaelpalacce** [comment]
> We are still developing new features e.g. we have implemented the new workflow items thing which was recently released to make incident troubleshooting easier for the 1st line guys

And you can still use those, no problem there @SimonSparksUK. The reality is that your maven modules (vra,vro,etc) can have different version. So I suggest your legacy vra 7 code, you can set to use v2.43.0 of the toolchain and all others you can upgrade.

Also keep in mind, I don't think any changes have really been done to the vra 7 archetype for years now.

**Comment by SimonSparksUK** [comment]
@Michaelpalacce I have sent you an email to clarify the size of our TypeScript project

**Comment by SimonSparksUK** [comment]
I was never able to get the build tools to push or pull component profiles for v7.6 I had to do these using cloud client

**Comment by Michaelpalacce** [comment]
@SimonSparksUK this is the place to have discussions regarding the toolchain, so that everyone can contribute and later if needed they can come back to the issues at hand. Either way I don't understand what you sent me. The structure?

**Comment by VenelinBakalov** [comment]
Adding a related samples PR which we need to merge together: https://github.com/vmware-samples/build-tools-for-vmware-aria-samples/pull/2
