### ISSUE TITLE
Update contact links in .github/ISSUE_TEMPLATE/config.yml

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#323]
### Description

https://github.com/vmware/build-tools-for-vmware-aria/blob/main/.github/ISSUE_TEMPLATE/config.yml is still pointing to slack, this needs to be updated, as now the best way to reach us would be github issues or discussions

**Comment by Patel-Vrushit** [comment]
Hi @Michaelpalacce I would like to help in resolving this issue. So could you give me a brief on how you expect it should work?
