### ISSUE TITLE
Canvas Item Decorators Error Handling

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#324]
### Description

The Decorators for different canvas elements have 2 possible states, one is the next element if all is good, the second is exception handling. 

We need to be able to support exception handling from element to element, giving us the ability to:
1. Point to the correct item if an exception is encountered
2. Bind an error to a variable if item supports it

Notes:
- The error binding must be done with an `@Err` decorator for the argument if possible. This may require nesting the extraction of argument decorator descriptors under the workflow item descriptors. Furthermore, it may be put under the same descriptor if needed
- Logic must be injected for error handlers in the Decorator Strategies.

**Comment by VenelinBakalov** [comment]
Implemented with https://github.com/vmware/build-tools-for-vmware-aria/pull/371
@Michaelpalacce we don't have anything else open for this one, right?
