### ISSUE TITLE
Remove Duplicate settings

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#328]
### Description

There are similar in meaning settings in the `settings.xml`: 

- `project.id` and `project.name`
- `org.id` and `org.name`

Similar properties are also present in the installer.

The ability to pass `id` should be entirely removed from BTVA and instead we should be using the `name` options as that will fetch the correct org or project. `id`s generally cause issues in Aria and BTVA when changing environments.

### Example

Use case for this would be:

You are developing a Windows template, you have a Project setup for that template, called `Windows` and you want to preserve that in another environment, if you use `id`s you will need to specify 1 id for each environment, however using `name` has no such problem.

### Notes

- Documentation needs to be updated accordingly
- We need to decide if we want `project.id` to still be usable and only add a deprecation warning or completely remove it.

**Comment by VenelinBakalov** [comment]
One more thing to clarify is if we completely remove, should we consider this as potential major change.

**Comment by VenelinBakalov** [comment]
@Michaelpalacce we had a short discussion regarding this topic, basically we should do it only if there is some hard benefit to it.
Should we do it, we need to consider:
1. Adding a deprecation warning during the push execution for 2.x and introduce the breaking change in 3.x
2. Do the same in the installer

**Comment by VenelinBakalov** [comment]
Whoever takes this, please note that this is a 2 step fix - 1 action item for the current major version and 1 future removal for 3.x milestone

**Comment by VenelinBakalov** [comment]
Agreed to execute this (as discussed above, in 2-step approach) as having both properties:
1. Leads to confusion in Built Tools consumers
2. Makes code handling more complex in any form of module extensions that use project or org identifiers
3. Leads to confusion when onboarding developers

**Comment by Michaelpalacce** [comment]
@VenelinBakalov Since we are working on 3.x.x, should we just remove it then? Or add a deprecation warning and do it for a later on release?
