### ISSUE TITLE
Problem with importing generated package into vRO

### ISSUE THREAD

**Issue by m15ch4** [vmware/build-tools-for-vmware-aria#33]
### Description

The import of the vRO package using vRO UI (vRA embedded) fails with the following error message:

`Failed to import package: Http failure response for https://vra01a.corp.lab/vco/api/packages/extendedImport: 400 OK`

When trying to push package using: `mvn package vrealize:push -Pcorp-dev` I get following error:

```
[INFO] Authentication strategy: 'VRA'
[INFO] Detecting vRO Server version '8.11.0.20963650'.
[INFO] Merge Package vrealize PushMojo: false
[INFO] STRATEGY| INFO | Apply Configuration strategies for import
[INFO] STRATEGY| PASS | Source.Version > Destination.Version
[INFO] PACKAGE | PASS | com.vmware.pscoe.library.ecmascript (2.29.2) > (missing)
[INFO] PACKAGE | PASS | pr2.test2 (1.0.0-SNAPSHOT) > (missing)
[INFO] Package | IMPORT | com.vmware.pscoe.library.ecmascript-2.29.2.package
[INFO] Package | IMPORT | pr2.test2-1.0.0-SNAPSHOT.package
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:45 min
[INFO] Finished at: 2023-03-01T14:34:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.29.2:push (default-cli) on project test2: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vrealize-package-maven-plugin:2.29.2:push failed: 400 Bad Request {"status":400,"message":"Unable to extract package from raw data"} -> [Help 1]
```

### Steps to Reproduce

1. Create project with: `mvn -X -U archetype:generate`. I used typescript based archetype (`com.vmware.pscoe.o11n.archetypes:package-typescript-archetype (package-typescript-archetype)`)
2. Build package with: `mvn clean package`. Package is build successfuly
3. Try importing generated package into vRO.

### Environment
Environment build mainly using these blog posts: https://www.brianmacinnes.com/configure-vrbt-for-vrealize-vra-vro-8-x/ and https://www.brianmacinnes.com/configure-artifactory-for-use-with-vmware-vrbt/
Instead of using bitnami artifactory, I installed new one on clean Debian VM.

#### Client

-   Build Tools for VMware Aria Version: v2.29.2
-   OS Version: Windows Server 2019

#### Server

-   vRealize Automation Version: 8.11
-   vRealize Orchestrator Version: 8.11

### Additional Context

Certificate used to sign packages was created using following commands:
```
openssl genpkey -out private_key.pem -algorithm RSA
openssl req -new -key private_key.pem -out csr.csr
openssl req -x509 -days 999 -key private_key.pem -in csr.csr -out cert.pem
```

**Comment by n-vodenicharski** [comment]
Workaround is to use the keys located in common/keystore-example/src/main/resources

**Comment by Michaelpalacce** [comment]
@m15ch4 closing this, feel free to re-open if needed
