### ISSUE TITLE
Canvas Item Decorator For Asynchronous Workflow Item

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#338]
### Description

We want to support the possibility to define an "Asynchronous Element" with a decorator

The Async Element can be used to execute a "Workflow" asynchronously, giving you back a workflow execution token that can be used to wait for the workflow to complete and consequently extract state/outputs from it.

### Example 

This is how the `workflow-item` looks like when we are dealing with an "Asynchronous Element":

```xml
  <workflow-item name="item3" out-name="item0" type="task" launched-workflow-id="9e4503db-cbaa-435a-9fad-144409c08df0">
    <display-name><![CDATA[Other Workflow]]></display-name>
    <script encoded="false"><![CDATA[//Auto generated script, cannot be modified !
var workflowToLaunch = Server.getWorkflowWithId("9e4503db-cbaa-435a-9fad-144409c08df0");
if (workflowToLaunch == null) {
	throw "Workflow not found";
}

var workflowParameters = new Properties();
workflowParameters.put("first",first);
workflowParameters.put("second",second);
wfToken = workflowToLaunch.execute(workflowParameters);
]]></script>
    <in-binding>
      <bind name="first" type="number" export-name="first"/>
      <bind name="second" type="number" export-name="second"/>
    </in-binding>
    <out-binding>
      <bind name="wfToken" type="WorkflowToken" export-name="wfToken"/>
    </out-binding>
    <description><![CDATA[Start an asynchronous workflow.]]></description>
    <position y="60.0" x="300.0"/>
  </workflow-item>
```

### Notes

- The auto generated code is actually needed, but we can do it in a different manner as long as it actually starts a workflow with the given parameters. 
  - This will require a separate `SourceFilePrinter` to handle this case. 
  - You can use the `ts.factory` to generate the code block.
- `launched-workflow-id` needs to be set as well, so the item looks correct in the canvas

**Comment by akantchev** [comment]
https://github.com/vmware/build-tools-for-vmware-aria/pull/354
