### ISSUE TITLE
Canvas Item Support for `End Workflow`

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#340]
### Description

We need to add support for "End workflow" elements, they are used to define "ends" of the wf.

### Example

Workflow ends can be one of two kinds:

Normal Ends:
```xml
  <workflow-item name="item6" business-status="Test Business status" type="end" end-mode="0">
    <in-binding/>
    <position y="50.0" x="400.0"/>
  </workflow-item>
```

Exception ends:
```xml
  <workflow-item name="item5" business-status="Bad" throw-bind-name="errorBind" type="end" end-mode="1">
    <in-binding/>
    <position y="210.0" x="320.0"/>
  </workflow-item>
```

### Notes

- We need to support both kinds of end
- `business-status` is completely optional, so it should be the same for us.
- `end-mode` signifies if it's good or bad. `1` means exception, `0` means normal end.
- `type` is always `end`
- `throw-bind-name` is the string variable that contains the error. Treat this as a normal attribute/input/output
- There will always be a default "end" that is targetable by passing "end" to the target, this will stay as is and will always be the last element that is generated.

**Comment by akantchev** [comment]
Implementation: https://github.com/vmware/build-tools-for-vmware-aria/pull/348
