### ISSUE TITLE
Inconsistency in handling non-versioned custom forms

### ISSUE THREAD

**Issue by sugeeshC** [vmware/build-tools-for-vmware-aria#342]
### Description

I attempted to reproduce the issue mentioned in [ this discussion ](https://github.com/vmware/build-tools-for-vmware-aria/discussions/257) using vRBT 2.38.0 and vRA version 8.16.0.3369. The original issue was reported on vRA version 8.16.2.

While I did not encounter the original error, there is a new inconsistency in how non-versioned custom forms are handled, as they are saved as versioned forms upon pushing. (Pulled non-versioned custom forms saving as versioned custom forms when pushing.)

### Steps to Reproduce

1. In vRA, create non-versioned custom form for cloud template based catalog item.
2. Pull the custom form to the local using vRBT.
3. Push the same, without changing anything.
4. Go to vRA and check the custom form.

**Expected behavior:**  Pulling and pushing the non-versioned custom form should be consistence. 

**Actual behavior:** Pulled non-versioned custom forms saving as versioned custom forms when pushing.

**Reproduces how often:** 100%

**Component/s:** common/artifact-manager

#### Client

-   Build Tools for VMware Aria Version: 2.38.0

#### Server

-   vRealize Automation Version: 8.16.0.3369

### Related Discussion

 [ related discussion ](https://github.com/vmware/build-tools-for-vmware-aria/discussions/257)

### Additional Context

This is when pulling and pushing to the SAME environment.

**Comment by sugeeshC** [comment]
After pulling the non-versioned custom form, removing following part from the catalog-items JSON file makes things consistent. So issue might be when pulling, adding this part on the catalog-items JSON file or when pushing, based on this field decide it is versioned or non-versioned form.

```
 "type": {
    "id": "com.vmw.blueprint"
  }
```

**Comment by Rehiq** [comment]
The tool itself is primarily made to be used with production version or to push the content and for the content to be usable in production - releases versions of Cloud templates of type Blueprint and Custom Forms, if any.
The functionality is deliberately done in such a manner.
