### ISSUE TITLE
Refactor Action Transformer

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#344]
### Description

General refactoring is needed of `typescript/vrotsc/src/compiler/transformer/fileTransformers/action.ts`.

### Notes

- Separate duplicate codes
- Eliminate private functions that inherit parent scope
- Documentation
- Other improvements

**Comment by SimonSparksUK** [comment]
Please add a DECORATOR for Actions as using the JSDoc for actions and a DECORATOR for everything else is a pain, it would be nice if everything was standardized to use DECORATORS.

![image](https://github.com/user-attachments/assets/d24d0878-208c-457c-ab6e-ce6f03a3404c)

![image](https://github.com/user-attachments/assets/1876c0ae-31ae-43aa-9067-6cd4e27c448f)

**Comment by Michaelpalacce** [comment]
@SimonSparksUK how would you propose we solve this in Javascript land then? Decorators are Typescript natives, not JS natives

**Comment by bcpmihail** [comment]
@SimonSparksUK Judging by this, decorators on pure functions aren't possible:
https://stackoverflow.com/questions/37518913/typescript-decorator-for-function-not-method-possible

**Comment by SimonSparksUK** [comment]
I was under the impression from the TypeScript documentation that you could apply a decorator to any method not just a class.

https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators

**Comment by SimonSparksUK** [comment]
The idea would be that the action decorator would provide all the extra information required to create an action e.g. inputs and their types and the output and its type etc...

**Comment by bcpmihail** [comment]
> I was under the impression from the TypeScript documentation that you could apply a decorator to any method not just a class.
> 
> https://www.typescriptlang.org/docs/handbook/decorators.html#method-decorators

Methods (member functions of a class) can be decorated. Functions (not part of a class, as in your example above) cannot be decorated, so what you are suggesting cannot be achieved within Typescript.

**Comment by Michaelpalacce** [comment]
Closing this, @bcpmihail research is valid
