### ISSUE TITLE
Add missing Aria types to `vro-types`

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#347]
### Description

Take a look at `vro-types/o11n-plugin-aria`. There are a lot of type declarations that are missing. Based on what is visible in the Api Explorer, we need to fill in whatever is missing.

**Comment by VenelinBakalov** [comment]
@unbreakabl3 is adding the missing types with the PRs linked above. In fact most of them are covered by him already so we might be able to close this one soon.
