### ISSUE TITLE
Size property of Map not working correctly

### ISSUE THREAD

**Issue by Gankarloo** [vmware/build-tools-for-vmware-aria#353]
### Description

The size propery of a Map is not updated when adding sets to the map.

### Steps to Reproduce

```javascript
var __global = System.getContext() || (function () { return this; }).call(null);
var VROES = __global.__VROES || (__global.__VROES = System.getModule("com.vmware.pscoe.library.ecmascript").VROES()), exports = {};
var Map = VROES.Map;

var myMap = new Map();
myMap.set(1,2);
System.log('myMap Size: '.concat(myMap.size)); // prints "myMap Size: 0"
```

**Expected behavior:** [What you expect to happen]
The size property should increase when adding to the Map.

**Actual behavior:** [What actually happens]
The size property seems to retain it's initial value.

**Reproduces how often:** [What percentage of the time does it reproduce]
100%
**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]
VROES

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]
2.40

#### Client

-   Build Tools for VMware Aria Version: 2.40
-   Visual Studio Code Version: 1.91.1
-   OS Version: Devcontainer Debian 12 on Windows 11(22H2)

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version: 8.17
-   vRealize Operations Version:
-   vRealize Log Insight Version:

### Additional Context

When instantiating the Map with initial values the size property is correctly updated.
```javascript
var M = new Map([[2, 2]]);
System.log(String(M.size)); // correctly prints 1
```
![image](https://github.com/user-attachments/assets/2003c453-2006-4dcc-889b-88686e680374)
![image](https://github.com/user-attachments/assets/3d803129-2b1b-480a-bc1f-d2b03cea567e)

**Comment by Gankarloo** [comment]
I believe the fault lies here in the if statement. 
https://github.com/vmware/build-tools-for-vmware-aria/blob/a0199d1b906460c96bd214f818d51a0ce2afe0f2/packages/ecmascript/src/Map.ts#L69

When the statement is negated it works as expected.

```typescript
if (!exist) {
    this.size++;
}
```

**Comment by Michaelpalacce** [comment]
The state e t should work, but perhaps `hasOwnProperty` is not what we need. Will take a look, seems like a bug.

**Comment by Gankarloo** [comment]
I think `hasOwnProperty` is fine.

First check if the key already exists.
if it exists don't increment the size counter, because the key will be overwritten.

As it is now the size is incremented each time a key is overweritten.
