### ISSUE TITLE
Maven assembly plugin 3.6.0 depends on com.github.luben:zstd-jni 1.5.5-2

### ISSUE THREAD

**Issue by pe1pip** [vmware/build-tools-for-vmware-aria#368]
### Description

Maven assembly plugin 3.6.0 depends on com.github.luben:zstd-jni 1.5.5-2, which is apparently insecure:

Maven assembly plugin 3.7.1 is available and should probably be used.

**Component/s:**

base-package
repository

**Affects Build/s:**

2.40.0 and older

#### Client

-   Build Tools for VMware Aria Version: 2.40.0
-   Visual Studio Code Version: latest
-   OS Version: n/a

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version:
-   vRealize Operations Version:
-   vRealize Log Insight Version:

**Comment by VenelinBakalov** [comment]
Closed by @pe1pip with https://github.com/vmware/build-tools-for-vmware-aria/pull/369 and to be included in the next release
