### ISSUE TITLE
Exclude test files during license header generation

### ISSUE THREAD

**Issue by VenelinBakalov** [vmware/build-tools-for-vmware-aria#379]
### Description

When generating project licensing using the license plugin we generate licenses for all `.js` and `.ts` files including tests. We want to update the plugin configuration to exclude test files both for JS and TS projects.

### Additional Context

This is achieved through `includes` and `excludes` properties in `pom.xml` files defined in the archetypes:
```xml
	<properties>
	        <license.includes>**/*.js,**/*.ts</license.includes>
        	<license.excludes></license.excludes>
	</properties>
```

This property needs to be updated to exclude `.test.ts` files and files under the `/src/test/`resources....` folder. An alternative for JS files would be to exclude files that end on `Test.js` and `Tests.js` which is the most common convention for javascript test files.
Sample configuration:
```xml
	<properties>
		<license.includes>**/*.js,**/*.ts</license.includes>
		<license.excludes>**/*.test.ts,**/*Test.js,**/*Tests.js</license.excludes>
	</properties>
```

Another alternative for ts files using regex:
```xml
<license.includes>%regex[^(?!.*test\.ts).*\.ts$]</license.includes>
```

This configuration must be updated in all archetypes that generate javascript and typescript code:

- https://github.com/vmware/build-tools-for-vmware-aria/blob/main/maven/archetypes/actions/src/main/resources/archetype-resources/pom.xml#L41
- https://github.com/vmware/build-tools-for-vmware-aria/blob/main/maven/archetypes/mixed/src/main/resources/archetype-resources/actions/pom.xml
- https://github.com/vmware/build-tools-for-vmware-aria/blob/main/maven/archetypes/ts-vra-ng/src/main/resources/archetype-resources/vro/pom.xml#L43
- https://github.com/vmware/build-tools-for-vmware-aria/blob/main/maven/archetypes/ts/src/main/resources/archetype-resources/pom.xml#L43

**Comment by VenelinBakalov** [comment]
After a bit of tests I am thinking we can use the following for JS:
```xml
<license.excludes>**/*.test.ts,test/resources/**/*.js</license.excludes>
```

**Comment by Michaelpalacce** [comment]
Maybe for another task, but also the license generation is messed up in some cases...

This is an example, but there may be more:
https://github.com/vmware/build-tools-for-vmware-aria/blob/50f070c8cd9fd2efc1628a9ccfe6034b8fc4a086/typescript/vrotsc/src/compiler/transformer/fileTransformers/workflow/workflow.ts#L137C2-L150C6

**Comment by VenelinBakalov** [comment]
Interesting, I will open a separate issue. Are there other locations that you know of?

**Comment by VenelinBakalov** [comment]
@Michaelpalacce opened a separate issue: https://github.com/vmware/build-tools-for-vmware-aria/issues/381

**Comment by VenelinBakalov** [comment]
Closed with https://github.com/vmware/build-tools-for-vmware-aria/pull/380
