### ISSUE TITLE
Fix wrong license generation within the tool itself

### ISSUE THREAD

**Issue by VenelinBakalov** [vmware/build-tools-for-vmware-aria#381]
### Description

Some of the license generation within the code of Built Tools for Aria is not working properly and is putting licenses between the code and not only as headers.

This is an example, but there may be more:
* https://github.com/vmware/build-tools-for-vmware-aria/blob/50f070c8cd9fd2efc1628a9ccfe6034b8fc4a086/typescript/vrotsc/src/compiler/transformer/fileTransformers/workflow/workflow.ts#L137C2-L150C6
* https://github.com/vmware/build-tools-for-vmware-aria/blob/main/typescript/polyglotpkg/src/packager.ts

**Expected behavior:** License headers are generated only on top of the source code.

**Actual behavior:** License headers are generated between code lines inside a file, e.g. above functions.

**Component/s:** [typescript/vrotsc] but there might be more

**Comment by Michaelpalacce** [comment]
Marking this as accepted, we need to fix this 100%

**Comment by VenelinBakalov** [comment]
Agreed
