### ISSUE TITLE
Make Policy Template version mandatory

### ISSUE THREAD

**Issue by bcpmihail** [vmware/build-tools-for-vmware-aria#393]
### Description

Full support for the Policy Feature was introduced 2 via adding new attributes to the Policy Template:
- templateVersion
- elements
- variables 
and makes the 'type' attribute obsolete.

To take advantage of these improvements, 'templateVersion': 'v2' is required.
However this can be easily missed as  the attribute is optional and its value defaults to 'v1' (for backward compatibility).
To avoid missing on the new functionality or confusion with the available versions, the 'templateVersion' attribute needs to be made mandatory.

As the Policy Template attributes are validated, this will be a breaking change (affecting all Policies built), requiring Major version release for BTVA and for https://github.com/vmware-samples/build-tools-for-vmware-aria-samples, where the sample and base-package version need to be updated.

### Additional Context

The issue is opened after discussion in:
https://github.com/vmware/build-tools-for-vmware-aria/issues/385

Introduction of full support for the Policy Feature:
https://github.com/vmware/build-tools-for-vmware-aria/pull/20

**Comment by Michaelpalacce** [comment]
Should we also default to v2 here?
