### ISSUE TITLE
Deprecate Module - export from

### ISSUE THREAD

**Issue by bcpmihail** [vmware/build-tools-for-vmware-aria#402]
### Description

In vroes/Module.ts, a function is assigned to Export.prototype.from; the function is not internally anywhere within BTVA, and 'from' is not part of the ModuleExport interface, which is why it needs to be deprecated or removed.

### Additional Context

Discussed on BTVA Roadmap meeting on Aug 29th, 2024.

**Comment by VenelinBakalov** [comment]
Since the function is completely not used and not exposed externally we can safely remove the function in the 2.x milestone
