### ISSUE TITLE
Bump license-maven-plugin versions

### ISSUE THREAD

**Issue by bb-erik** [vmware/build-tools-for-vmware-aria#405]
### Description
I would appreciate if you can update the dependency of license-maven-plugin, but of course you can bump all of them in the pomfile. :)
Thank you!

**Comment by VenelinBakalov** [comment]
Hi @bb-erik , thanks for the suggestion. 
Regarding the licensing plugin, sounds good, is there any particular version or functionality you are looking into or "latest and greatest"? 
Regarding other plugins, I would suggest to open any specific plugin requests as a separate issue similar to this one, this way we would have good separation and it would be easiest to track, develop and release.

**Comment by bb-erik** [comment]
Thank you for the fast response @VenelinBakalov!
Latest version for the license-maven-plugin (2.4.0) would be good.
At this point I only need that plugin bumped. If the need for the other ones arises, I will open individual Issues. 
Thank you!

**Comment by VenelinBakalov** [comment]
@bb-erik issue should be solved with https://github.com/vmware/build-tools-for-vmware-aria/pull/409
At least on my local tests it seems everything is compiling and licenses are being generated the same with 2.4.0. I will keep you posted when we release so you can validate on your side as well.

Another option that I can suggest in case you want to test this early, you can download the repository, checkout the latest main and follow the steps in `How to build -> 2. execute` to push a build in your local repository. After that in your project you can point the parent artifact to version 2.41.1-SNAPSHOT which is pushed in your local maven repo, and test.
 https://github.com/vmware/build-tools-for-vmware-aria/blob/main/README.md

**Comment by VenelinBakalov** [comment]
Released with 2.42.0 and available in Maven central:
https://github.com/vmware/build-tools-for-vmware-aria/releases/tag/v2.42.0

**Comment by VenelinBakalov** [comment]
@bb-erik fyi
