### ISSUE TITLE
Declaration mapping

### ISSUE THREAD

**Issue by Indy-rbo** [vmware/build-tools-for-vmware-aria#416]
### Description

To improve the Developer Experience I'd love to have it so that clicking on an imported dependency opens the actual file, instead of opening a `*.d.ts` file only showing the type declarations.

There is the [`declarationMap`](https://www.typescriptlang.org/tsconfig/#declarationMap) setting for `tsconfig.json` which states:

> Generates a source map for .d.ts files which map back to the original .ts source file. This will allow editors such as VS Code to go to the original .ts file when using features like Go to Definition.
>
> You should strongly consider turning this on if you’re using project references.

But setting that locally didn't seem to change anything for me.
Should this already be possible to do? Otherwise I would like to request the Build Tools to do this for us.

**Comment by Michaelpalacce** [comment]
Taking this one, I want to research it

**Comment by VenelinBakalov** [comment]
We did an internal discussion plus research on this one - unfortunately at the current state there is no way to workaround this and implement a viable solution. Unfortunately we don't have all the benefits of pure NodeJS implementation and we are limited in different ways here.
