### ISSUE TITLE
v2.42.0 ecmascript problem

### ISSUE THREAD

**Issue by unbreakabl3** [vmware/build-tools-for-vmware-aria#417]
### Description

Getting this error, when trying to execute a workflow

```
2024-09-13 13:43:09.391 +02:00 ERROR (com.vmware.pscoe.library.ecmascript/Module) Error in (Dynamic Script Module name : Module#18) ReferenceError: "exports" is not defined.
2024-09-13 13:43:09.428 +02:00 ERROR Workflow execution stack:
```

This doesn't happen in 2.41.0

### Steps to Reproduce

1. Create a TS project and create a new workflow
2. Create a new TS class and import it into the WF
3. Build the project and run the workflow

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:** [What you expect to happen]

Workflow will run as expected
**Actual behavior:** [What actually happens]

Workflow is failing

**Reproduces how often:** [What percentage of the time does it reproduce]

All the time

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]

typescript/ecmascript

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

#### Client

-   Build Tools for VMware Aria Version: 2.42.0
-   Visual Studio Code Version: 1.19.0
-   OS Version: MacOS

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version: 8.16,8.17
-   vRealize Operations Version:
-   vRealize Log Insight Version:

**Comment by VenelinBakalov** [comment]
Interesting, truly the transpiled code results into an undefined "exports" param:
<img width="1042" alt="image" src="https://github.com/user-attachments/assets/9d470d71-cf24-4d9d-ba7d-abee93185df7">

**Comment by bcpmihail** [comment]
The error was caused by an exported constant in Module.ts:
```
export const DEFAULT_MODULE_ERROR_HANDLER: ModuleErrorHandler = (error) => System.error(error?.toString());
```
The "exports" variable is not added when the Action is of type function/closure - see [prologue](https://github.com/vmware/build-tools-for-vmware-aria/blob/8e86f9e726880d509d6088672bfd58ed01d926e7/typescript/vrotsc/src/compiler/transformer/codeTransformers/prologueStatements.ts#L230-L238) , which I believe is the intended behaviour.

**Comment by VenelinBakalov** [comment]
Fixed, we will plan a bugfix release this week to cover that.

**Comment by VenelinBakalov** [comment]
Btw @unbreakabl3 thank you for notifying us for this issue! As always, great catch!
