### ISSUE TITLE
Workflow Decorators Issue in vRO TS Project

### ISSUE THREAD

**Issue by unbreakabl3** [vmware/build-tools-for-vmware-aria#422]
### Description

Hi,
I am following the documentation [here](https://github.com/vmware/build-tools-for-vmware-aria/blob/main/docs/versions/latest/Components/Archetypes/typescript/Components/Workflows.md) and getting this error below for any kind of decorator when trying to test it. 
**The code is built without an issues.**

![image](https://github.com/user-attachments/assets/506e1182-e7cf-49ae-9bb5-9a1033aad164)

Unfortunately, I am not sure I can get where/why it's coming from. Maybe someone can help?

### Steps to Reproduce

1. Create a test workflow
2. Follow the provided documentation and create an `@Item` decorator.
3. See the VSCode error

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce]

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]

`typescript/vrotsc-annotations`

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

#### Client

-   Build Tools for VMware Aria Version: 2.41.0
-   Visual Studio Code Version: 1.19
-   OS Version: MacOS

#### Server

-   vRealize Automation Version:
-   vRealize Orchestrator Version: 8.16,8.17
-   vRealize Operations Version:
-   vRealize Log Insight Version:

**Comment by Michaelpalacce** [comment]
Can you give us details about what's on your environment?

- `mvn --version`
- `node --version`
- `npm list -g --depth 0`

Have you done any changes to the `tsconfig.json` file?

**Comment by unbreakabl3** [comment]
You're right. Good point.`"strictNullChecks": true` in `tsconfig.json` caused that. 
Can be closed I think. Thanks a lot for your help.

**Comment by Michaelpalacce** [comment]
No worries. Just a general message for all who find this. The `tsconfig.json` is there entirely for IDEs' sake. We generate our own `tsconfig` file when building, so changes to the one you have in your project will not affect the build
