### ISSUE TITLE
Add support for latest Node.js LTS version

### ISSUE THREAD

**Issue by pboychev-bcom** [vmware/build-tools-for-vmware-aria#464]
### Description

Go through all TypeScript components and test with the latest Node.js LTS version.  
Fix the code to add support for the new version wherever issues are found.

**Comment by VenelinBakalov** [comment]
Isn't this a duplicate to this issue:
https://github.com/vmware/build-tools-for-vmware-aria/issues/332

**Comment by Michaelpalacce** [comment]
@pboychev-bcom, closing this as duplicate
