### ISSUE TITLE
Remove src/license/THIRD-PARTY.properties file from the generated vro package

### ISSUE THREAD

**Issue by ivo-kotev** [vmware/build-tools-for-vmware-aria#469]
### Description

When `mvn clean package` command is triggered, maven - using the license plugin will obtain the license agreement for each dependency. This information will be used to generate the `src/license/THIRD-PARTY.properties` file.
This file is important to keep track for the license details for each dependency but does not make any sense to be part of the generated vRO package.
Problem: This file is included in each vRO package and appears in vRO as resource element, while it's not intended to be included in the vRO content.

### Additional Context

Several options are available to fix this issue:

1. Exclude `src/license/THIRD-PARTY.properties` from the `src` files that are going to converted to vRO package
1. Exclude all files that does not have `.element_info.json` or `.element_info.yaml` and do not treat them by default as Resource Elements (this approach will most probably lead to regression for projects that used this bug as a feature)
1. Change the default location where the file is generated, to be outside of the SRC directory (https://www.mojohaus.org/license-maven-plugin/add-third-party-mojo.html)

**Comment by VenelinBakalov** [comment]
Since we are currently in development of 3.x.x I would suggesting going for option 2.
Just a question, is this logic happening somewhere in vropkg?

**Comment by Michaelpalacce** [comment]
I am for enforcing `element_info`

**Comment by Michaelpalacce** [comment]
Right, so I went for approach `3.` since we didn't get this in for version 3, and I don't think it's worth it

**Comment by VenelinBakalov** [comment]
@Michaelpalacce if you want to go for approach 2 it is still fine as well, we announced that the breaking changes will come in 3.x and the following release so it is ok to introduce another breaking change now

**Comment by Michaelpalacce** [comment]
@VenelinBakalov I am not 100% sure if it's the right thing. Chances are people are using that...
