### ISSUE TITLE
Unable to package `ABX` project

### ISSUE THREAD

**Issue by VenelinBakalov** [vmware/build-tools-for-vmware-aria#484]
### Description

When running `mvn clean package` on an ABX project an error is thrown.

[Description of the issue. Affected functionality / feature.]

### Steps to Reproduce

1. Create a sample project using the following script
```
mvn archetype:generate \
    -DinteractiveMode=false \
    -DarchetypeGroupId=com.vmware.pscoe.polyglot.archetypes \
    -DarchetypeArtifactId=package-polyglot-archetype \
    -DarchetypeVersion=2.44.0 \
    -DgroupId=local.corp.devops.common \
    -DartifactId=testAbxProject \
    -Dtype=abx
```
2. Run `mvn clean package`

**Expected behavior:** [What you expect to happen]
The project packages successfully.

**Actual behavior:** [What actually happens]
The following error is thrown:
`[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:abx-package-maven-plugin:2.44.0:package (default-package) on project anothertest: Error creating ABX bundle: duplicate entry: node_modules/run-script-os/index.js -> [Help 1]`

**Reproduces how often:** 100%

**Affects Build/s:**
2.44.0

#### Client

-   Build Tools for VMware Aria Version: 2.44.0
-   Visual Studio Code Version: 1.93.1 (Universal)
-   OS Version: MacOS Sonoma 14.5

### Failure Logs

![image](https://github.com/user-attachments/assets/b683655e-045d-4e30-8640-999de8c7b46f)

### Additional Context

Please, after fixing the build issue try also pushing to make sure that the push manages to successfully deliver the created package to vRO.
`mvn clean package vrealize:push -P<profileName>`

**Comment by vasyl-vs** [comment]
I will look on it

**Comment by Michaelpalacce** [comment]
@vasyl-vs I see you took on another task, what is the status of this one?

**Comment by VenelinBakalov** [comment]
@Michaelpalacce sorry, I saw your comment too late, we discussed it few days ago, there was something minor to check with Niki but all is clear now and a PR is opened.
