### ISSUE TITLE
Fail to assign a default value to Workflow's Attributes

### ISSUE THREAD

**Issue by IoannisF-NRB** [vmware/build-tools-for-vmware-aria#514]
### Description

We have some workflows that have some attributes we need with default fixed values. When we build the package and import it to our environment, the values defined for our attributes are empty.

### Steps to Reproduce

1. This is my Workflow decorator configuration : 
![image](https://github.com/user-attachments/assets/172bc443-558f-418f-bbff-e80048f96a3e)

2. I package my vro project with the following command `mvn clean package`
3. I import my newly generated package to my environment
4. I check my workflow and I can see my attributes but their values are empty
![image](https://github.com/user-attachments/assets/074b7432-d880-4c48-90e4-d86543445d2d)

**Expected behavior:** 
I expect to see my defined values in the attributes

**Actual behavior:** 
I cannot see my values, they are empty

**Reproduces how often:** 
All the time

**Component/s:** 
@types/vrotsc-annotations
@vmware-pscoe/vrotsc

**Affects Build/s:** 
2.44.0

#### Client

-   Build Tools for VMware Aria Version: 2.44.0
-   Visual Studio Code Version: 1.95.2
-   OS Version: Win 11

#### Server

-   vRealize Automation Version: 8.18.0.35770 (24024333)
-   vRealize Orchestrator Version: 8.18.0.24015865

**Comment by Michaelpalacce** [comment]
Can confirm:

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/34c14317-5b00-4b7a-87da-bc9106e81a23">


Looking into this. Can you send me the generated files in the target folder if possible? Specifically what was generated in:

`target/vro-sources`

**Comment by Michaelpalacce** [comment]
Right, I found the issue... It's a giant mess whatever happened. 

This is where the first issue is: 

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/54903e0c-7fd7-4748-a159-74695f59a5db">

This only seems to work if there is a `att.bind`, but that shouldn't be the case... even then ... it works with `defaultValue` which is not correct, as it should work with `value` ....
