### ISSUE TITLE
Bundle extra folders with the installer when doing `-Pbundle-with-installer`

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#539]
> ### Description
There is a need of having several files and directories coming as part of the bundle (artifact), hence it will be good if we have a way  to choose data from the repository to be exported and be bundled. Example of such data ins installJson file, which is used by workflow installer (more examples can be given on demand). To achieve this, we can use pom.xml file in parent directory, adding a property for export, ex:
cat pom.xml
```
...
        <properties>
		<maven.deploy.skip>true</maven.deploy.skip>
		<generated.from>ts-vra-ng</generated.from>
		<additional.bundle.content>"infrastructure-specs/response-files/install_wf.yaml","infrastructure-specs/response-files/environment.properties","integration-tests/"</additional.bundle.content>
	</properties>
	<build>
		<plugins>
...
```
We can store all of these exports within bin directory (configurable ?). Also, it is good to add some checks like:
- file/directory doesn't exist -> mvn build error
- export if a file not from repository ("../../some_file.txt") --> mvn build error

**Comment by uthery** [comment]
> ### Description
There is a need of having several files and directories coming as part of the bundle (artifact), hence it will be good if we have a way  to choose data from the repository to be exported and be bundled. Example of such data ins installJson file, which is used by workflow installer (more examples can be given on demand). To achieve this, we can use pom.xml file in parent directory, adding a property for export, ex:
cat pom.xml
```
...
        <properties>
		<maven.deploy.skip>true</maven.deploy.skip>
		<generated.from>ts-vra-ng</generated.from>
		<additional.bundle.content>"infrastructure-specs/response-files/install_wf.yaml","infrastructure-specs/response-files/environment.properties","integration-tests/"</additional.bundle.content>
	</properties>
	<build>
		<plugins>
...
```
We can store all of these exports within bin directory (configurable ?). Also, it is good to add some checks like:
- file/directory doesn't exist -> mvn build error
- export if a file not from repository ("../../some_file.txt") --> mvn build error
> ### Alternatives
> ### Additional Context
