### ISSUE TITLE
vro authentication failure with vro.auth=vra

### ISSUE THREAD

**Issue by pe1pip** [vmware/build-tools-for-vmware-aria#74]
### Description

When using vra auth with username and password stored in a server stanza in the settings.xml this fails. The vra auth splits username and domain on the first @ character in the username. In our environment we use a full eMail address as username (active directory userPrincipalName), because this is the only field that uniquely identifies the user in the company. So a full username becomes user@example.com@example.domain

### Steps to Reproduce

create a user with an @ in the username
try setting up vRBT for vro with vra auth

**Preconditions:**

**Expected behavior:**

The code in common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/Configuration.java that splits the username from the domain uses the first @ for the split, while in fact it should use the last @

**Actual behavior:**

The code in common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/Configuration.java that splits the username from the domain uses the first @ for the split, while in fact it should use the last @

leverage String.lastIndexOf('@')

**Reproduces how often:**

100%

**Component/s:**

The code in common/artifact-manager/src/main/java/com/vmware/pscoe/iac/artifact/configuration/Configuration.java:

```
    public String getUsername() {
        String username = this.properties.getProperty(USERNAME);
        return StringUtils.isEmpty(username) ? username : username.replaceAll("@.*", "");
    }

    public String getDomain() {
        String username = this.properties.getProperty(USERNAME);
        return StringUtils.isEmpty(username) ? username
                : (username.indexOf("@") > 0 ? username.substring(username.indexOf("@") + 1) : null);
    }
```

maybe fix as:

```
    public String getUsername() {
        String username = this.properties.getProperty(USERNAME);
        return StringUtils.isEmpty(username) ? username
               : (username.indexOf("@") > 0 ?  username.substring(0, username.lastIndexOf("@")) : username);
    }

    public String getDomain() {
        String username = this.properties.getProperty(USERNAME);
        return StringUtils.isEmpty(username) ? username
                : (username.indexOf("@") > 0 ? username.substring(username.lastIndexOf("@") + 1) : null);
    }
```

**Affects Build/s:**

2.30.0 and up

#### Client

-   Build Tools for VMware Aria Version: 2.30.0 / 2.31.0
-   Visual Studio Code Version: n/a
-   OS Version: macOs 13.2.1 / rhel 8 / win 10

#### Server

-   vRealize Automation Version: 8.11
-   vRealize Orchestrator Version: 8.11
-   vRealize Operations Version: n/a
-   vRealize Log Insight Version: n/a

**Comment by Michaelpalacce** [comment]
@vmware/build-tools-for-vmware-aria-maintainers lets triage this?

**Comment by Michaelpalacce** [comment]
Hey @pe1pip,

It was decided that we will change the detection to detect the final `@` as you suggested.
