### ISSUE TITLE
Unable to omit 'region-mapping' from the content.yaml

### ISSUE THREAD

**Issue by RV1959** [vmware/build-tools-for-vmware-aria#76]
I want to extract only a portion of the vRA 8 content to the Visual Studio Code project, so in the content.yaml I specified:

region-mapping: []

However when I do so, the following error results when I pull:

[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.31.1:pull (default-cli) on project test: Execution default-cli of goal com.vmware.pscoe.maven.plugins:vra-ng-package-maven-plugin:2.31.1:pull failed: Unable to load vRA Package Descriptor[E:\Users\xxx\repositories\temp\test\content.yaml]: Cannot deserialize value of type `com.vmware.pscoe.iac.artifact.model.vrang.VraNgRegionMapping` from Array value (token `JsonToken.START_ARRAY`)
[ERROR]  at [Source: (File); line: 32, column: 17] (through reference chain: com.vmware.pscoe.iac.artifact.model.vrang.VraNgPackageDescriptor["region-mapping"])
[ERROR] -> [Help 1]

So, it seems that the Build Tools currently cannot handle an empty array for region-mapping.
When I comment out this line, by default I get a lot of files that I do not want in my project.

Can you please update the Build Tools to accept an empty array everywhere, to avoid pulling files that are not desired?

Thanks, Roberto

**Comment by Michaelpalacce** [comment]
Hey @RV1959,

That's expected.

region-mapping is an object, you are trying to re-assign it to an array. Furthermore we do expect cloud-account-tags and all else to be present. 

To omit region-mappings, you can try:

```yml
region-mapping:
  cloud-account-tags:
    export-tag: ""
    import-tags: []
```
