### ISSUE TITLE
Using vro:pull on a JS actions project fails on SAX dependency error

### ISSUE THREAD

**Issue by simplygeekuk** [vmware/build-tools-for-vmware-aria#85]
### Description

[Description of the issue. Affected functionality / feature.]
Running vro:pull results with a NodeJS dependency error with module SAX

### Steps to Reproduce
mvn vro:pull -P#profile name -pl #js actions project

**Expected behavior:** [What you expect to happen]
Actions to be pulled from vRO Server

**Actual behavior:** 
Fails with error (see Failure Logs below)

**Reproduces how often:** 100%

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]

#### Client

-   Build Tools for VMware Aria Version: 2.26.3
-   Visual Studio Code Version: 1.77.3
-   vRealize Developer Tool: 2.4.0
-   OS Version: Windows 10

#### Server

-   vRealize Automation Version: 8.11.1
-   vRealize Orchestrator Version: 8.11.1

### Failure Logs
[ERROR] C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:651
[ERROR]     er = new Error(er)
[ERROR]          ^
[ERROR]
[ERROR] Error: Non-whitespace before first tag.
[ERROR] Line: 0
[ERROR] Column: 1
[ERROR] Char: o
[ERROR]     at error (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:651:10)
[ERROR]     at strictFail (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:677:7)
[ERROR]     at beginWhiteSpace (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:951:7)     
[ERROR]     at SAXParser.write (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\node_modules\sax\lib\sax.js:1006:11)   
[ERROR]     at new XmlDocument (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\node_modules\xmldoc\lib\xmldoc.js:295:17)
[ERROR]     at exports.xml (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\util.js:13:25)
[ERROR]     at C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:65:27
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:4:12)
[ERROR]     at parseFlatElement (C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:21:47)
[ERROR]     at C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:101:22
[ERROR]     at Array.map (<anonymous>)
[ERROR]     at C:\Users\xxxxxxxx\projects\vrealize\vmware\js\actions\node_modules\@vmware-pscoe\vropkg\dist\parse\flat.js:101:10
[ERROR]     at Generator.next (<anonymous>)
[ERROR]
[ERROR] Node.js v18.16.0
[INFO] Running vropkg... finished
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.965 s
[INFO] Finished at: 2023-04-21T16:05:35+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-actions-package-maven-plugin:2.26.3:pull (default-cli) on project js.actions: Running vropkg... failed with code 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Michaelpalacce** [comment]
Hey @simplygeekuk you should be using NodeJS 14 or 16. 18 is known to have issues, can you try downgrading and giving it a try?

**Comment by simplygeekuk** [comment]
Hi @Michaelpalacce 

I can confirm this was the issue. Reverting to NodeJS 16 now works.

Thanks,

Gavin
