### ISSUE TITLE
Issue executing package vrealize:push vrotsc cannot transpile module names with dash separators

### ISSUE THREAD

**Issue by veselinss** [vmware/build-tools-for-vmware-aria#89]
### Description

If the "vrotsc-annotations" module, or any other that does not have a "." or "/", is in use in a project, once compiled to js the variable name for the module contains a "-". This renders any classes that use such annotations useless.

### Steps to Reproduce

1. Create a VRO-typescript project or mixed project
2. Import the "vrotsc-annotations" module in a class
3. Execute a maven build with compile stage active or vrealize:push 

**Expected behavior:**  
Successful build with no errors and only working .js files in target

**Actual behavior:** 
Some classes are rendered unusable, hence once pushed the package does not fully work.

**Reproduces how often:** 
100%

**Component/s:** 
vrotsc

**Affects Build/s:** 
2.31.0

-   Build Tools for VMware Aria Version:  2.31.0
-   vRealize Developer Tools: 2.4.0
-   Visual Studio Code Version: 1.77.3
-   OS Version: Windows_NT x64 10.0.22621 / Ubuntu 22.04.1 LTS
-   Maven Version:  3.8.8 / 3.6.3
-   Java Version: 17.0.7 / 17.0.6
-   Node.js Version: 14.17.1 / 14.20.0
-   Npm Version: 6.14.13 / 6.14.17

**Server**
-   vRealize Automation Version: 8.11.1
-   vRealize Orchestrator Version: 8.11.1

### Failure Logs

[INFO] info: Parsing vro javascript project folder path "/home/xxxxxxxx/vro/target/vro-sources/js"...
[ERROR] (node:11131) UnhandledPromiseRejectionWarning: Error: /home/xxxxxxxx/vro/target/vro-sources/js/src/main/resources/xxxxxxxx/vro/elements/config/SmtpConfiguration.js [10:15]: Unexpected token: '-'
[ERROR]  SyntaxError: [10:15]: Unexpected token: '-'
[ERROR]     at report (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:186:11)
[ERROR]     at matchOrInsertSemicolon (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4368:9)
[ERROR]     at parseVariableStatement (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:5365:5)
[ERROR]     at parseStatement (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4906:20)
[ERROR]     at parseStatementListItem (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4900:20)
[ERROR]     at parseFunctionBody (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6106:19)
[ERROR]     at parseFunctionExpression (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6703:18)
[ERROR]     at parsePrimaryExpression (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6381:20)
[ERROR]     at parseParenthesizedExpression (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:7681:20)
[ERROR]     at parsePrimaryExpression (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6387:20)
[ERROR]     at parseExpressionOrLabelledStatement (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4965:20)
[ERROR]     at parseStatement (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4950:20)
[ERROR]     at parseStatementListItem (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4900:20)
[ERROR]     at parseModuleItem (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4864:26)
[ERROR]     at parseModuleItemList (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4849:25)
[ERROR]     at parseSource (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4793:16)
[ERROR]     at Function.getSourceTreeFromSource (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:210:19)
[ERROR]     at VroJsProjParser.<anonymous> (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:50:50)
[ERROR]     at Array.forEach (<anonymous>)
[ERROR]     at VroJsProjParser.<anonymous> (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:32:69)
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at /home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:4:12)
[ERROR]     at VroJsProjParser.parse (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:27:16)
[ERROR]     at /home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/cli.js:112:57
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at /home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/cli.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/cli.js:4:12)
[ERROR]     at run (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/cli.js:54:12)
[ERROR]     at Object.<anonymous> (/home/xxxxxxxx/vro/node_modules/@vmware-pscoe/vropkg/dist/cli.js:151:1)
[ERROR] (Use `node --trace-warnings ...` to show where the warning was created)
[ERROR] (node:11131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[ERROR] (node:11131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Michaelpalacce** [comment]
Are you sure? Seems to me like you are trying to compile a configurationElement and you've forgotten to name it configName.conf.ts?

Also, `or any other that does not have a "." or "/",` is hard to understand... What do you mean?

**Comment by Michaelpalacce** [comment]
Just to note:

Config elements follow the schema:

`CONFIG_ELEMENT_NAME.conf.ts`

Workflows:

`WF_ELEMENT_NAME.wf.ts` The error you are seeing happens if these are normally miss-named

**Comment by Michaelpalacce** [comment]
Closing as resolved
